// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace EPayments.Admin.Controllers
{
    public partial class EserviceClientController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected EserviceClientController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult List()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.List);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ListSearch()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ListSearch);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ListSort()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ListSort);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult View()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.View);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Edit()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Edit);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Delete()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Delete);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AddVpos()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddVpos);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AddVposDsk()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddVposDsk);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ViewVposDsk()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ViewVposDsk);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult EditVposDsk()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditVposDsk);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DeleteVposDsk()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteVposDsk);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AddVposBorica()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddVposBorica);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ViewVposBorica()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ViewVposBorica);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult EditVposBorica()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditVposBorica);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DeleteVposBorica()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteVposBorica);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult HideVposBoricaWarning()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.HideVposBoricaWarning);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AddVposFibank()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddVposFibank);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ViewVposFibank()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ViewVposFibank);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult EditVposFibank()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditVposFibank);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DeleteVposFibank()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteVposFibank);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AddEformsUser()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddEformsUser);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ViewEformsUser()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ViewEformsUser);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult EditEformsUser()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditEformsUser);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult EditEformsUserPassword()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditEformsUserPassword);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DeleteEformsUser()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteEformsUser);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public EserviceClientController Actions { get { return MVC.EserviceClient; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "EserviceClient";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "EserviceClient";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string List = "List";
            public readonly string ListSearch = "ListSearch";
            public readonly string ListSort = "ListSort";
            public readonly string View = "View";
            public readonly string Create = "Create";
            public readonly string Edit = "Edit";
            public readonly string Delete = "Delete";
            public readonly string AddVpos = "AddVpos";
            public readonly string AddVposDsk = "AddVposDsk";
            public readonly string ViewVposDsk = "ViewVposDsk";
            public readonly string EditVposDsk = "EditVposDsk";
            public readonly string DeleteVposDsk = "DeleteVposDsk";
            public readonly string AddVposBorica = "AddVposBorica";
            public readonly string ViewVposBorica = "ViewVposBorica";
            public readonly string EditVposBorica = "EditVposBorica";
            public readonly string DeleteVposBorica = "DeleteVposBorica";
            public readonly string HideVposBoricaWarning = "HideVposBoricaWarning";
            public readonly string AddVposFibank = "AddVposFibank";
            public readonly string ViewVposFibank = "ViewVposFibank";
            public readonly string EditVposFibank = "EditVposFibank";
            public readonly string DeleteVposFibank = "DeleteVposFibank";
            public readonly string AddEformsUser = "AddEformsUser";
            public readonly string ViewEformsUser = "ViewEformsUser";
            public readonly string EditEformsUser = "EditEformsUser";
            public readonly string EditEformsUserPassword = "EditEformsUserPassword";
            public readonly string DeleteEformsUser = "DeleteEformsUser";
            public readonly string DownloadUserManual = "DownloadUserManual";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string List = "List";
            public const string ListSearch = "ListSearch";
            public const string ListSort = "ListSort";
            public const string View = "View";
            public const string Create = "Create";
            public const string Edit = "Edit";
            public const string Delete = "Delete";
            public const string AddVpos = "AddVpos";
            public const string AddVposDsk = "AddVposDsk";
            public const string ViewVposDsk = "ViewVposDsk";
            public const string EditVposDsk = "EditVposDsk";
            public const string DeleteVposDsk = "DeleteVposDsk";
            public const string AddVposBorica = "AddVposBorica";
            public const string ViewVposBorica = "ViewVposBorica";
            public const string EditVposBorica = "EditVposBorica";
            public const string DeleteVposBorica = "DeleteVposBorica";
            public const string HideVposBoricaWarning = "HideVposBoricaWarning";
            public const string AddVposFibank = "AddVposFibank";
            public const string ViewVposFibank = "ViewVposFibank";
            public const string EditVposFibank = "EditVposFibank";
            public const string DeleteVposFibank = "DeleteVposFibank";
            public const string AddEformsUser = "AddEformsUser";
            public const string ViewEformsUser = "ViewEformsUser";
            public const string EditEformsUser = "EditEformsUser";
            public const string EditEformsUserPassword = "EditEformsUserPassword";
            public const string DeleteEformsUser = "DeleteEformsUser";
            public const string DownloadUserManual = "DownloadUserManual";
        }


        static readonly ActionParamsClass_List s_params_List = new ActionParamsClass_List();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_List ListParams { get { return s_params_List; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_List
        {
            public readonly string searchDO = "searchDO";
        }
        static readonly ActionParamsClass_ListSearch s_params_ListSearch = new ActionParamsClass_ListSearch();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ListSearch ListSearchParams { get { return s_params_ListSearch; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ListSearch
        {
            public readonly string searchDO = "searchDO";
        }
        static readonly ActionParamsClass_ListSort s_params_ListSort = new ActionParamsClass_ListSort();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ListSort ListSortParams { get { return s_params_ListSort; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ListSort
        {
            public readonly string searchDO = "searchDO";
        }
        static readonly ActionParamsClass_View s_params_View = new ActionParamsClass_View();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_View ViewParams { get { return s_params_View; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_View
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_Create s_params_Create = new ActionParamsClass_Create();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Create CreateParams { get { return s_params_Create; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Create
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_Edit s_params_Edit = new ActionParamsClass_Edit();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Edit EditParams { get { return s_params_Edit; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Edit
        {
            public readonly string id = "id";
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_Delete s_params_Delete = new ActionParamsClass_Delete();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Delete DeleteParams { get { return s_params_Delete; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Delete
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_AddVpos s_params_AddVpos = new ActionParamsClass_AddVpos();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddVpos AddVposParams { get { return s_params_AddVpos; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddVpos
        {
            public readonly string id = "id";
            public readonly string type = "type";
        }
        static readonly ActionParamsClass_AddVposDsk s_params_AddVposDsk = new ActionParamsClass_AddVposDsk();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddVposDsk AddVposDskParams { get { return s_params_AddVposDsk; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddVposDsk
        {
            public readonly string id = "id";
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_ViewVposDsk s_params_ViewVposDsk = new ActionParamsClass_ViewVposDsk();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ViewVposDsk ViewVposDskParams { get { return s_params_ViewVposDsk; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ViewVposDsk
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_EditVposDsk s_params_EditVposDsk = new ActionParamsClass_EditVposDsk();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_EditVposDsk EditVposDskParams { get { return s_params_EditVposDsk; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_EditVposDsk
        {
            public readonly string id = "id";
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_DeleteVposDsk s_params_DeleteVposDsk = new ActionParamsClass_DeleteVposDsk();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteVposDsk DeleteVposDskParams { get { return s_params_DeleteVposDsk; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteVposDsk
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_AddVposBorica s_params_AddVposBorica = new ActionParamsClass_AddVposBorica();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddVposBorica AddVposBoricaParams { get { return s_params_AddVposBorica; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddVposBorica
        {
            public readonly string id = "id";
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_ViewVposBorica s_params_ViewVposBorica = new ActionParamsClass_ViewVposBorica();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ViewVposBorica ViewVposBoricaParams { get { return s_params_ViewVposBorica; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ViewVposBorica
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_EditVposBorica s_params_EditVposBorica = new ActionParamsClass_EditVposBorica();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_EditVposBorica EditVposBoricaParams { get { return s_params_EditVposBorica; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_EditVposBorica
        {
            public readonly string id = "id";
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_DeleteVposBorica s_params_DeleteVposBorica = new ActionParamsClass_DeleteVposBorica();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteVposBorica DeleteVposBoricaParams { get { return s_params_DeleteVposBorica; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteVposBorica
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_HideVposBoricaWarning s_params_HideVposBoricaWarning = new ActionParamsClass_HideVposBoricaWarning();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_HideVposBoricaWarning HideVposBoricaWarningParams { get { return s_params_HideVposBoricaWarning; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_HideVposBoricaWarning
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_AddVposFibank s_params_AddVposFibank = new ActionParamsClass_AddVposFibank();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddVposFibank AddVposFibankParams { get { return s_params_AddVposFibank; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddVposFibank
        {
            public readonly string id = "id";
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_ViewVposFibank s_params_ViewVposFibank = new ActionParamsClass_ViewVposFibank();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ViewVposFibank ViewVposFibankParams { get { return s_params_ViewVposFibank; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ViewVposFibank
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_EditVposFibank s_params_EditVposFibank = new ActionParamsClass_EditVposFibank();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_EditVposFibank EditVposFibankParams { get { return s_params_EditVposFibank; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_EditVposFibank
        {
            public readonly string id = "id";
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_DeleteVposFibank s_params_DeleteVposFibank = new ActionParamsClass_DeleteVposFibank();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteVposFibank DeleteVposFibankParams { get { return s_params_DeleteVposFibank; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteVposFibank
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_AddEformsUser s_params_AddEformsUser = new ActionParamsClass_AddEformsUser();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddEformsUser AddEformsUserParams { get { return s_params_AddEformsUser; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddEformsUser
        {
            public readonly string id = "id";
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_ViewEformsUser s_params_ViewEformsUser = new ActionParamsClass_ViewEformsUser();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ViewEformsUser ViewEformsUserParams { get { return s_params_ViewEformsUser; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ViewEformsUser
        {
            public readonly string id = "id";
            public readonly string eserviceAdminUserId = "eserviceAdminUserId";
        }
        static readonly ActionParamsClass_EditEformsUser s_params_EditEformsUser = new ActionParamsClass_EditEformsUser();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_EditEformsUser EditEformsUserParams { get { return s_params_EditEformsUser; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_EditEformsUser
        {
            public readonly string id = "id";
            public readonly string eserviceAdminUserId = "eserviceAdminUserId";
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_EditEformsUserPassword s_params_EditEformsUserPassword = new ActionParamsClass_EditEformsUserPassword();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_EditEformsUserPassword EditEformsUserPasswordParams { get { return s_params_EditEformsUserPassword; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_EditEformsUserPassword
        {
            public readonly string id = "id";
            public readonly string eserviceAdminUserId = "eserviceAdminUserId";
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_DeleteEformsUser s_params_DeleteEformsUser = new ActionParamsClass_DeleteEformsUser();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteEformsUser DeleteEformsUserParams { get { return s_params_DeleteEformsUser; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteEformsUser
        {
            public readonly string id = "id";
            public readonly string eserviceAdminUserId = "eserviceAdminUserId";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string AddEformsUser = "AddEformsUser";
                public readonly string AddVposBorica = "AddVposBorica";
                public readonly string AddVposDsk = "AddVposDsk";
                public readonly string AddVposFibank = "AddVposFibank";
                public readonly string Create = "Create";
                public readonly string Edit = "Edit";
                public readonly string EditEformsUser = "EditEformsUser";
                public readonly string EditEformsUserPassword = "EditEformsUserPassword";
                public readonly string EditVposBorica = "EditVposBorica";
                public readonly string EditVposDsk = "EditVposDsk";
                public readonly string EditVposFibank = "EditVposFibank";
                public readonly string EserviceVM = "EserviceVM";
                public readonly string Form = "Form";
                public readonly string FormEformsUser = "FormEformsUser";
                public readonly string FormVposBorica = "FormVposBorica";
                public readonly string FormVposDsk = "FormVposDsk";
                public readonly string FormVposFibank = "FormVposFibank";
                public readonly string List = "List";
                public readonly string View = "View";
                public readonly string ViewEformsUser = "ViewEformsUser";
                public readonly string ViewVposBorica = "ViewVposBorica";
                public readonly string ViewVposDsk = "ViewVposDsk";
                public readonly string ViewVposFibank = "ViewVposFibank";
            }
            public readonly string AddEformsUser = "~/Views/EserviceClient/AddEformsUser.cshtml";
            public readonly string AddVposBorica = "~/Views/EserviceClient/AddVposBorica.cshtml";
            public readonly string AddVposDsk = "~/Views/EserviceClient/AddVposDsk.cshtml";
            public readonly string AddVposFibank = "~/Views/EserviceClient/AddVposFibank.cshtml";
            public readonly string Create = "~/Views/EserviceClient/Create.cshtml";
            public readonly string Edit = "~/Views/EserviceClient/Edit.cshtml";
            public readonly string EditEformsUser = "~/Views/EserviceClient/EditEformsUser.cshtml";
            public readonly string EditEformsUserPassword = "~/Views/EserviceClient/EditEformsUserPassword.cshtml";
            public readonly string EditVposBorica = "~/Views/EserviceClient/EditVposBorica.cshtml";
            public readonly string EditVposDsk = "~/Views/EserviceClient/EditVposDsk.cshtml";
            public readonly string EditVposFibank = "~/Views/EserviceClient/EditVposFibank.cshtml";
            public readonly string EserviceVM = "~/Views/EserviceClient/EserviceVM.cshtml";
            public readonly string Form = "~/Views/EserviceClient/Form.cshtml";
            public readonly string FormEformsUser = "~/Views/EserviceClient/FormEformsUser.cshtml";
            public readonly string FormVposBorica = "~/Views/EserviceClient/FormVposBorica.cshtml";
            public readonly string FormVposDsk = "~/Views/EserviceClient/FormVposDsk.cshtml";
            public readonly string FormVposFibank = "~/Views/EserviceClient/FormVposFibank.cshtml";
            public readonly string List = "~/Views/EserviceClient/List.cshtml";
            public readonly string View = "~/Views/EserviceClient/View.cshtml";
            public readonly string ViewEformsUser = "~/Views/EserviceClient/ViewEformsUser.cshtml";
            public readonly string ViewVposBorica = "~/Views/EserviceClient/ViewVposBorica.cshtml";
            public readonly string ViewVposDsk = "~/Views/EserviceClient/ViewVposDsk.cshtml";
            public readonly string ViewVposFibank = "~/Views/EserviceClient/ViewVposFibank.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_EserviceClientController : EPayments.Admin.Controllers.EserviceClientController
    {
        public T4MVC_EserviceClientController() : base(Dummy.Instance) { }

        [NonAction]
        partial void ListOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, EPayments.Admin.DataObjects.ListSearchDO searchDO);

        [NonAction]
        public override System.Web.Mvc.ActionResult List(EPayments.Admin.DataObjects.ListSearchDO searchDO)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.List);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchDO", searchDO);
            ListOverride(callInfo, searchDO);
            return callInfo;
        }

        [NonAction]
        partial void ListSearchOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, EPayments.Admin.DataObjects.ListSearchDO searchDO);

        [NonAction]
        public override System.Web.Mvc.ActionResult ListSearch(EPayments.Admin.DataObjects.ListSearchDO searchDO)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ListSearch);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchDO", searchDO);
            ListSearchOverride(callInfo, searchDO);
            return callInfo;
        }

        [NonAction]
        partial void ListSortOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, EPayments.Admin.DataObjects.ListSearchDO searchDO);

        [NonAction]
        public override System.Web.Mvc.ActionResult ListSort(EPayments.Admin.DataObjects.ListSearchDO searchDO)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ListSort);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchDO", searchDO);
            ListSortOverride(callInfo, searchDO);
            return callInfo;
        }

        [NonAction]
        partial void ViewOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult View(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.View);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ViewOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void CreateOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Create()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Create);
            CreateOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void CreateOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, EPayments.Admin.Models.EserviceClient.EServiceClientVM model);

        [NonAction]
        public override System.Web.Mvc.ActionResult Create(EPayments.Admin.Models.EserviceClient.EServiceClientVM model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Create);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            CreateOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void EditOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult Edit(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Edit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            EditOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void EditOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id, EPayments.Admin.Models.EserviceClient.EServiceClientVM model);

        [NonAction]
        public override System.Web.Mvc.ActionResult Edit(int id, EPayments.Admin.Models.EserviceClient.EServiceClientVM model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Edit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            EditOverride(callInfo, id, model);
            return callInfo;
        }

        [NonAction]
        partial void DeleteOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult Delete(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Delete);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DeleteOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void AddVposOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id, EPayments.Model.Enums.Vpos? type);

        [NonAction]
        public override System.Web.Mvc.ActionResult AddVpos(int id, EPayments.Model.Enums.Vpos? type)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddVpos);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "type", type);
            AddVposOverride(callInfo, id, type);
            return callInfo;
        }

        [NonAction]
        partial void AddVposDskOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult AddVposDsk(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddVposDsk);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            AddVposDskOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void AddVposDskOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id, EPayments.Admin.Models.EserviceClient.VposDskVM model);

        [NonAction]
        public override System.Web.Mvc.ActionResult AddVposDsk(int id, EPayments.Admin.Models.EserviceClient.VposDskVM model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddVposDsk);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            AddVposDskOverride(callInfo, id, model);
            return callInfo;
        }

        [NonAction]
        partial void ViewVposDskOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult ViewVposDsk(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ViewVposDsk);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ViewVposDskOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void EditVposDskOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult EditVposDsk(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditVposDsk);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            EditVposDskOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void EditVposDskOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id, EPayments.Admin.Models.EserviceClient.VposDskVM model);

        [NonAction]
        public override System.Web.Mvc.ActionResult EditVposDsk(int id, EPayments.Admin.Models.EserviceClient.VposDskVM model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditVposDsk);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            EditVposDskOverride(callInfo, id, model);
            return callInfo;
        }

        [NonAction]
        partial void DeleteVposDskOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult DeleteVposDsk(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteVposDsk);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DeleteVposDskOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void AddVposBoricaOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult AddVposBorica(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddVposBorica);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            AddVposBoricaOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void AddVposBoricaOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id, EPayments.Admin.Models.EserviceClient.VposBoricaVM model);

        [NonAction]
        public override System.Web.Mvc.ActionResult AddVposBorica(int id, EPayments.Admin.Models.EserviceClient.VposBoricaVM model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddVposBorica);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            AddVposBoricaOverride(callInfo, id, model);
            return callInfo;
        }

        [NonAction]
        partial void ViewVposBoricaOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult ViewVposBorica(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ViewVposBorica);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ViewVposBoricaOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void EditVposBoricaOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult EditVposBorica(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditVposBorica);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            EditVposBoricaOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void EditVposBoricaOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id, EPayments.Admin.Models.EserviceClient.VposBoricaVM model);

        [NonAction]
        public override System.Web.Mvc.ActionResult EditVposBorica(int id, EPayments.Admin.Models.EserviceClient.VposBoricaVM model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditVposBorica);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            EditVposBoricaOverride(callInfo, id, model);
            return callInfo;
        }

        [NonAction]
        partial void DeleteVposBoricaOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult DeleteVposBorica(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteVposBorica);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DeleteVposBoricaOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void HideVposBoricaWarningOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult HideVposBoricaWarning(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.HideVposBoricaWarning);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            HideVposBoricaWarningOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void AddVposFibankOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult AddVposFibank(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddVposFibank);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            AddVposFibankOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void AddVposFibankOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id, EPayments.Admin.Models.EserviceClient.VposFibankVM model);

        [NonAction]
        public override System.Web.Mvc.ActionResult AddVposFibank(int id, EPayments.Admin.Models.EserviceClient.VposFibankVM model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddVposFibank);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            AddVposFibankOverride(callInfo, id, model);
            return callInfo;
        }

        [NonAction]
        partial void ViewVposFibankOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult ViewVposFibank(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ViewVposFibank);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ViewVposFibankOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void EditVposFibankOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult EditVposFibank(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditVposFibank);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            EditVposFibankOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void EditVposFibankOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id, EPayments.Admin.Models.EserviceClient.VposFibankVM model);

        [NonAction]
        public override System.Web.Mvc.ActionResult EditVposFibank(int id, EPayments.Admin.Models.EserviceClient.VposFibankVM model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditVposFibank);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            EditVposFibankOverride(callInfo, id, model);
            return callInfo;
        }

        [NonAction]
        partial void DeleteVposFibankOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult DeleteVposFibank(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteVposFibank);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DeleteVposFibankOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void AddEformsUserOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult AddEformsUser(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddEformsUser);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            AddEformsUserOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void AddEformsUserOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id, EPayments.Admin.Models.EserviceClient.EformsUserVM model);

        [NonAction]
        public override System.Web.Mvc.ActionResult AddEformsUser(int id, EPayments.Admin.Models.EserviceClient.EformsUserVM model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddEformsUser);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            AddEformsUserOverride(callInfo, id, model);
            return callInfo;
        }

        [NonAction]
        partial void ViewEformsUserOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id, int eserviceAdminUserId);

        [NonAction]
        public override System.Web.Mvc.ActionResult ViewEformsUser(int id, int eserviceAdminUserId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ViewEformsUser);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "eserviceAdminUserId", eserviceAdminUserId);
            ViewEformsUserOverride(callInfo, id, eserviceAdminUserId);
            return callInfo;
        }

        [NonAction]
        partial void EditEformsUserOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id, int eserviceAdminUserId);

        [NonAction]
        public override System.Web.Mvc.ActionResult EditEformsUser(int id, int eserviceAdminUserId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditEformsUser);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "eserviceAdminUserId", eserviceAdminUserId);
            EditEformsUserOverride(callInfo, id, eserviceAdminUserId);
            return callInfo;
        }

        [NonAction]
        partial void EditEformsUserOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id, int eserviceAdminUserId, EPayments.Admin.Models.EserviceClient.EformsUserVM model);

        [NonAction]
        public override System.Web.Mvc.ActionResult EditEformsUser(int id, int eserviceAdminUserId, EPayments.Admin.Models.EserviceClient.EformsUserVM model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditEformsUser);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "eserviceAdminUserId", eserviceAdminUserId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            EditEformsUserOverride(callInfo, id, eserviceAdminUserId, model);
            return callInfo;
        }

        [NonAction]
        partial void EditEformsUserPasswordOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id, int eserviceAdminUserId);

        [NonAction]
        public override System.Web.Mvc.ActionResult EditEformsUserPassword(int id, int eserviceAdminUserId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditEformsUserPassword);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "eserviceAdminUserId", eserviceAdminUserId);
            EditEformsUserPasswordOverride(callInfo, id, eserviceAdminUserId);
            return callInfo;
        }

        [NonAction]
        partial void EditEformsUserPasswordOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id, int eserviceAdminUserId, EPayments.Admin.Models.EserviceClient.EformsUserPasswordVM model);

        [NonAction]
        public override System.Web.Mvc.ActionResult EditEformsUserPassword(int id, int eserviceAdminUserId, EPayments.Admin.Models.EserviceClient.EformsUserPasswordVM model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditEformsUserPassword);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "eserviceAdminUserId", eserviceAdminUserId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            EditEformsUserPasswordOverride(callInfo, id, eserviceAdminUserId, model);
            return callInfo;
        }

        [NonAction]
        partial void DeleteEformsUserOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id, int eserviceAdminUserId);

        [NonAction]
        public override System.Web.Mvc.ActionResult DeleteEformsUser(int id, int eserviceAdminUserId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteEformsUser);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "eserviceAdminUserId", eserviceAdminUserId);
            DeleteEformsUserOverride(callInfo, id, eserviceAdminUserId);
            return callInfo;
        }

        [NonAction]
        partial void DownloadUserManualOverride(T4MVC_System_Web_Mvc_FileResult callInfo);

        [NonAction]
        public override System.Web.Mvc.FileResult DownloadUserManual()
        {
            var callInfo = new T4MVC_System_Web_Mvc_FileResult(Area, Name, ActionNames.DownloadUserManual);
            DownloadUserManualOverride(callInfo);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
