// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace EPayments.Web.Controllers
{
    public partial class AisController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected AisController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult PaymentOrder()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PaymentOrder);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult PrintOrder()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PrintOrder);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.FileResult DownloadPdfOrder()
        {
            return new T4MVC_System_Web_Mvc_FileResult(Area, Name, ActionNames.DownloadPdfOrder);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public AisController Actions { get { return MVC.Ais; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Ais";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Ais";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string PaymentOrder = "PaymentOrder";
            public readonly string PrintOrder = "PrintOrder";
            public readonly string DownloadPdfOrder = "DownloadPdfOrder";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string PaymentOrder = "PaymentOrder";
            public const string PrintOrder = "PrintOrder";
            public const string DownloadPdfOrder = "DownloadPdfOrder";
        }


        static readonly ActionParamsClass_PaymentOrder s_params_PaymentOrder = new ActionParamsClass_PaymentOrder();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PaymentOrder PaymentOrderParams { get { return s_params_PaymentOrder; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PaymentOrder
        {
            public readonly string requestDO = "requestDO";
        }
        static readonly ActionParamsClass_PrintOrder s_params_PrintOrder = new ActionParamsClass_PrintOrder();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PrintOrder PrintOrderParams { get { return s_params_PrintOrder; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PrintOrder
        {
            public readonly string requestDO = "requestDO";
        }
        static readonly ActionParamsClass_DownloadPdfOrder s_params_DownloadPdfOrder = new ActionParamsClass_DownloadPdfOrder();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DownloadPdfOrder DownloadPdfOrderParams { get { return s_params_DownloadPdfOrder; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DownloadPdfOrder
        {
            public readonly string requestDO = "requestDO";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
            }
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_AisController : EPayments.Web.Controllers.AisController
    {
        public T4MVC_AisController() : base(Dummy.Instance) { }

        [NonAction]
        partial void PaymentOrderOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, EPayments.Common.DataObjects.AuthRequestDO requestDO);

        [NonAction]
        public override System.Web.Mvc.ActionResult PaymentOrder(EPayments.Common.DataObjects.AuthRequestDO requestDO)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PaymentOrder);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "requestDO", requestDO);
            PaymentOrderOverride(callInfo, requestDO);
            return callInfo;
        }

        [NonAction]
        partial void PrintOrderOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, EPayments.Common.DataObjects.AuthRequestDO requestDO);

        [NonAction]
        public override System.Web.Mvc.ActionResult PrintOrder(EPayments.Common.DataObjects.AuthRequestDO requestDO)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PrintOrder);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "requestDO", requestDO);
            PrintOrderOverride(callInfo, requestDO);
            return callInfo;
        }

        [NonAction]
        partial void DownloadPdfOrderOverride(T4MVC_System_Web_Mvc_FileResult callInfo, EPayments.Common.DataObjects.AuthRequestDO requestDO);

        [NonAction]
        public override System.Web.Mvc.FileResult DownloadPdfOrder(EPayments.Common.DataObjects.AuthRequestDO requestDO)
        {
            var callInfo = new T4MVC_System_Web_Mvc_FileResult(Area, Name, ActionNames.DownloadPdfOrder);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "requestDO", requestDO);
            DownloadPdfOrderOverride(callInfo, requestDO);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
