// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace EPayments.Web.Controllers
{
    public partial class EserviceAdminController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected EserviceAdminController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult PaymentRequests()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PaymentRequests);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult PaymentRequestsSearch()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PaymentRequestsSearch);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult PaymentRequestsSort()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PaymentRequestsSort);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult PaymentRequestsExportAsPdf()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PaymentRequestsExportAsPdf);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult PaymentRequestsExportAsExcel()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PaymentRequestsExportAsExcel);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> SuspendRequest()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SuspendRequest);
            return System.Threading.Tasks.Task.FromResult(callInfo as ActionResult);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> SetStatusPaid()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SetStatusPaid);
            return System.Threading.Tasks.Task.FromResult(callInfo as ActionResult);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult PrintPaymentRequests()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PrintPaymentRequests);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult TransactionList()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.TransactionList);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult TransactionListSearch()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.TransactionListSearch);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult TransactionListSort()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.TransactionListSort);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult TransactionDetails()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.TransactionDetails);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult TransactionReferencedPayment()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.TransactionReferencedPayment);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult PrintOrder()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PrintOrder);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.FileResult DownloadPdfOrder()
        {
            return new T4MVC_System_Web_Mvc_FileResult(Area, Name, ActionNames.DownloadPdfOrder);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Settings()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Settings);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult TransactionListExportExcel()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.TransactionListExportExcel);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult TransactionListExportHtml()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.TransactionListExportHtml);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult TransactionListExportXml()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.TransactionListExportXml);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult TransactionListPrintHtml()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.TransactionListPrintHtml);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public EserviceAdminController Actions { get { return MVC.EserviceAdmin; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "EserviceAdmin";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "EserviceAdmin";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string PaymentRequests = "PaymentRequests";
            public readonly string PaymentRequestsSearch = "PaymentRequestsSearch";
            public readonly string PaymentRequestsSort = "PaymentRequestsSort";
            public readonly string PaymentRequestsExportAsPdf = "PaymentRequestsExportAsPdf";
            public readonly string PaymentRequestsExportAsExcel = "PaymentRequestsExportAsExcel";
            public readonly string CreatePaymentRequest = "CreatePaymentRequest";
            public readonly string SuspendRequest = "SuspendRequest";
            public readonly string SetStatusPaid = "SetStatusPaid";
            public readonly string PrintPaymentRequests = "PrintPaymentRequests";
            public readonly string TransactionList = "TransactionList";
            public readonly string TransactionListSearch = "TransactionListSearch";
            public readonly string TransactionListSort = "TransactionListSort";
            public readonly string TransactionDetails = "TransactionDetails";
            public readonly string TransactionReferencedPayment = "TransactionReferencedPayment";
            public readonly string PrintOrder = "PrintOrder";
            public readonly string DownloadPdfOrder = "DownloadPdfOrder";
            public readonly string EditSettings = "EditSettings";
            public readonly string Settings = "Settings";
            public readonly string TransactionListExportExcel = "TransactionListExportExcel";
            public readonly string TransactionListExportHtml = "TransactionListExportHtml";
            public readonly string TransactionListExportXml = "TransactionListExportXml";
            public readonly string TransactionListPrintHtml = "TransactionListPrintHtml";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string PaymentRequests = "PaymentRequests";
            public const string PaymentRequestsSearch = "PaymentRequestsSearch";
            public const string PaymentRequestsSort = "PaymentRequestsSort";
            public const string PaymentRequestsExportAsPdf = "PaymentRequestsExportAsPdf";
            public const string PaymentRequestsExportAsExcel = "PaymentRequestsExportAsExcel";
            public const string CreatePaymentRequest = "CreatePaymentRequest";
            public const string SuspendRequest = "SuspendRequest";
            public const string SetStatusPaid = "SetStatusPaid";
            public const string PrintPaymentRequests = "PrintPaymentRequests";
            public const string TransactionList = "TransactionList";
            public const string TransactionListSearch = "TransactionListSearch";
            public const string TransactionListSort = "TransactionListSort";
            public const string TransactionDetails = "TransactionDetails";
            public const string TransactionReferencedPayment = "TransactionReferencedPayment";
            public const string PrintOrder = "PrintOrder";
            public const string DownloadPdfOrder = "DownloadPdfOrder";
            public const string EditSettings = "EditSettings";
            public const string Settings = "Settings";
            public const string TransactionListExportExcel = "TransactionListExportExcel";
            public const string TransactionListExportHtml = "TransactionListExportHtml";
            public const string TransactionListExportXml = "TransactionListExportXml";
            public const string TransactionListPrintHtml = "TransactionListPrintHtml";
        }


        static readonly ActionParamsClass_PaymentRequests s_params_PaymentRequests = new ActionParamsClass_PaymentRequests();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PaymentRequests PaymentRequestsParams { get { return s_params_PaymentRequests; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PaymentRequests
        {
            public readonly string searchDO = "searchDO";
        }
        static readonly ActionParamsClass_PaymentRequestsSearch s_params_PaymentRequestsSearch = new ActionParamsClass_PaymentRequestsSearch();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PaymentRequestsSearch PaymentRequestsSearchParams { get { return s_params_PaymentRequestsSearch; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PaymentRequestsSearch
        {
            public readonly string searchDO = "searchDO";
        }
        static readonly ActionParamsClass_PaymentRequestsSort s_params_PaymentRequestsSort = new ActionParamsClass_PaymentRequestsSort();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PaymentRequestsSort PaymentRequestsSortParams { get { return s_params_PaymentRequestsSort; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PaymentRequestsSort
        {
            public readonly string searchDO = "searchDO";
        }
        static readonly ActionParamsClass_PaymentRequestsExportAsPdf s_params_PaymentRequestsExportAsPdf = new ActionParamsClass_PaymentRequestsExportAsPdf();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PaymentRequestsExportAsPdf PaymentRequestsExportAsPdfParams { get { return s_params_PaymentRequestsExportAsPdf; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PaymentRequestsExportAsPdf
        {
            public readonly string searchDO = "searchDO";
        }
        static readonly ActionParamsClass_PaymentRequestsExportAsExcel s_params_PaymentRequestsExportAsExcel = new ActionParamsClass_PaymentRequestsExportAsExcel();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PaymentRequestsExportAsExcel PaymentRequestsExportAsExcelParams { get { return s_params_PaymentRequestsExportAsExcel; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PaymentRequestsExportAsExcel
        {
            public readonly string searchDO = "searchDO";
        }
        static readonly ActionParamsClass_CreatePaymentRequest s_params_CreatePaymentRequest = new ActionParamsClass_CreatePaymentRequest();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CreatePaymentRequest CreatePaymentRequestParams { get { return s_params_CreatePaymentRequest; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CreatePaymentRequest
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_SuspendRequest s_params_SuspendRequest = new ActionParamsClass_SuspendRequest();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SuspendRequest SuspendRequestParams { get { return s_params_SuspendRequest; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SuspendRequest
        {
            public readonly string gid = "gid";
        }
        static readonly ActionParamsClass_SetStatusPaid s_params_SetStatusPaid = new ActionParamsClass_SetStatusPaid();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SetStatusPaid SetStatusPaidParams { get { return s_params_SetStatusPaid; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SetStatusPaid
        {
            public readonly string gid = "gid";
            public readonly string paymentMethod = "paymentMethod";
        }
        static readonly ActionParamsClass_PrintPaymentRequests s_params_PrintPaymentRequests = new ActionParamsClass_PrintPaymentRequests();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PrintPaymentRequests PrintPaymentRequestsParams { get { return s_params_PrintPaymentRequests; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PrintPaymentRequests
        {
            public readonly string searchDO = "searchDO";
            public readonly string printAllResults = "printAllResults";
        }
        static readonly ActionParamsClass_TransactionList s_params_TransactionList = new ActionParamsClass_TransactionList();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_TransactionList TransactionListParams { get { return s_params_TransactionList; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_TransactionList
        {
            public readonly string searchDO = "searchDO";
        }
        static readonly ActionParamsClass_TransactionListSearch s_params_TransactionListSearch = new ActionParamsClass_TransactionListSearch();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_TransactionListSearch TransactionListSearchParams { get { return s_params_TransactionListSearch; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_TransactionListSearch
        {
            public readonly string searchDO = "searchDO";
        }
        static readonly ActionParamsClass_TransactionListSort s_params_TransactionListSort = new ActionParamsClass_TransactionListSort();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_TransactionListSort TransactionListSortParams { get { return s_params_TransactionListSort; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_TransactionListSort
        {
            public readonly string searchDO = "searchDO";
        }
        static readonly ActionParamsClass_TransactionDetails s_params_TransactionDetails = new ActionParamsClass_TransactionDetails();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_TransactionDetails TransactionDetailsParams { get { return s_params_TransactionDetails; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_TransactionDetails
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_TransactionReferencedPayment s_params_TransactionReferencedPayment = new ActionParamsClass_TransactionReferencedPayment();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_TransactionReferencedPayment TransactionReferencedPaymentParams { get { return s_params_TransactionReferencedPayment; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_TransactionReferencedPayment
        {
            public readonly string id = "id";
            public readonly string showDetailsForm = "showDetailsForm";
        }
        static readonly ActionParamsClass_PrintOrder s_params_PrintOrder = new ActionParamsClass_PrintOrder();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PrintOrder PrintOrderParams { get { return s_params_PrintOrder; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PrintOrder
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_DownloadPdfOrder s_params_DownloadPdfOrder = new ActionParamsClass_DownloadPdfOrder();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DownloadPdfOrder DownloadPdfOrderParams { get { return s_params_DownloadPdfOrder; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DownloadPdfOrder
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_EditSettings s_params_EditSettings = new ActionParamsClass_EditSettings();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_EditSettings EditSettingsParams { get { return s_params_EditSettings; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_EditSettings
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_Settings s_params_Settings = new ActionParamsClass_Settings();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Settings SettingsParams { get { return s_params_Settings; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Settings
        {
            public readonly string searchDO = "searchDO";
        }
        static readonly ActionParamsClass_TransactionListExportExcel s_params_TransactionListExportExcel = new ActionParamsClass_TransactionListExportExcel();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_TransactionListExportExcel TransactionListExportExcelParams { get { return s_params_TransactionListExportExcel; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_TransactionListExportExcel
        {
            public readonly string searchDO = "searchDO";
        }
        static readonly ActionParamsClass_TransactionListExportHtml s_params_TransactionListExportHtml = new ActionParamsClass_TransactionListExportHtml();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_TransactionListExportHtml TransactionListExportHtmlParams { get { return s_params_TransactionListExportHtml; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_TransactionListExportHtml
        {
            public readonly string searchDO = "searchDO";
        }
        static readonly ActionParamsClass_TransactionListExportXml s_params_TransactionListExportXml = new ActionParamsClass_TransactionListExportXml();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_TransactionListExportXml TransactionListExportXmlParams { get { return s_params_TransactionListExportXml; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_TransactionListExportXml
        {
            public readonly string searchDO = "searchDO";
        }
        static readonly ActionParamsClass_TransactionListPrintHtml s_params_TransactionListPrintHtml = new ActionParamsClass_TransactionListPrintHtml();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_TransactionListPrintHtml TransactionListPrintHtmlParams { get { return s_params_TransactionListPrintHtml; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_TransactionListPrintHtml
        {
            public readonly string searchDO = "searchDO";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string CreatePaymentRequest = "CreatePaymentRequest";
                public readonly string EditSettings = "EditSettings";
                public readonly string PaymentRequestDOForm = "PaymentRequestDOForm";
                public readonly string PaymentRequests = "PaymentRequests";
                public readonly string PrintPaymentRequests = "PrintPaymentRequests";
                public readonly string Settings = "Settings";
                public readonly string TransactionDetails = "TransactionDetails";
                public readonly string TransactionList = "TransactionList";
                public readonly string TransactionListPrintHtml = "TransactionListPrintHtml";
            }
            public readonly string CreatePaymentRequest = "~/Views/EserviceAdmin/CreatePaymentRequest.cshtml";
            public readonly string EditSettings = "~/Views/EserviceAdmin/EditSettings.cshtml";
            public readonly string PaymentRequestDOForm = "~/Views/EserviceAdmin/PaymentRequestDOForm.cshtml";
            public readonly string PaymentRequests = "~/Views/EserviceAdmin/PaymentRequests.cshtml";
            public readonly string PrintPaymentRequests = "~/Views/EserviceAdmin/PrintPaymentRequests.cshtml";
            public readonly string Settings = "~/Views/EserviceAdmin/Settings.cshtml";
            public readonly string TransactionDetails = "~/Views/EserviceAdmin/TransactionDetails.cshtml";
            public readonly string TransactionList = "~/Views/EserviceAdmin/TransactionList.cshtml";
            public readonly string TransactionListPrintHtml = "~/Views/EserviceAdmin/TransactionListPrintHtml.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_EserviceAdminController : EPayments.Web.Controllers.EserviceAdminController
    {
        public T4MVC_EserviceAdminController() : base(Dummy.Instance) { }

        [NonAction]
        partial void PaymentRequestsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, EPayments.Web.DataObjects.EserviceAdminRequestSearchDO searchDO);

        [NonAction]
        public override System.Web.Mvc.ActionResult PaymentRequests(EPayments.Web.DataObjects.EserviceAdminRequestSearchDO searchDO)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PaymentRequests);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchDO", searchDO);
            PaymentRequestsOverride(callInfo, searchDO);
            return callInfo;
        }

        [NonAction]
        partial void PaymentRequestsSearchOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, EPayments.Web.DataObjects.EserviceAdminRequestSearchDO searchDO);

        [NonAction]
        public override System.Web.Mvc.ActionResult PaymentRequestsSearch(EPayments.Web.DataObjects.EserviceAdminRequestSearchDO searchDO)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PaymentRequestsSearch);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchDO", searchDO);
            PaymentRequestsSearchOverride(callInfo, searchDO);
            return callInfo;
        }

        [NonAction]
        partial void PaymentRequestsSortOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, EPayments.Web.DataObjects.EserviceAdminRequestSearchDO searchDO);

        [NonAction]
        public override System.Web.Mvc.ActionResult PaymentRequestsSort(EPayments.Web.DataObjects.EserviceAdminRequestSearchDO searchDO)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PaymentRequestsSort);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchDO", searchDO);
            PaymentRequestsSortOverride(callInfo, searchDO);
            return callInfo;
        }

        [NonAction]
        partial void PaymentRequestsExportAsPdfOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, EPayments.Web.DataObjects.EserviceAdminRequestSearchDO searchDO);

        [NonAction]
        public override System.Web.Mvc.ActionResult PaymentRequestsExportAsPdf(EPayments.Web.DataObjects.EserviceAdminRequestSearchDO searchDO)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PaymentRequestsExportAsPdf);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchDO", searchDO);
            PaymentRequestsExportAsPdfOverride(callInfo, searchDO);
            return callInfo;
        }

        [NonAction]
        partial void PaymentRequestsExportAsExcelOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, EPayments.Web.DataObjects.EserviceAdminRequestSearchDO searchDO);

        [NonAction]
        public override System.Web.Mvc.ActionResult PaymentRequestsExportAsExcel(EPayments.Web.DataObjects.EserviceAdminRequestSearchDO searchDO)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PaymentRequestsExportAsExcel);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchDO", searchDO);
            PaymentRequestsExportAsExcelOverride(callInfo, searchDO);
            return callInfo;
        }

        [NonAction]
        partial void CreatePaymentRequestOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult CreatePaymentRequest()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CreatePaymentRequest);
            CreatePaymentRequestOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void CreatePaymentRequestOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, EPayments.Web.DataObjects.PaymentRequestDO model);

        [NonAction]
        public override System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> CreatePaymentRequest(EPayments.Web.DataObjects.PaymentRequestDO model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CreatePaymentRequest);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            CreatePaymentRequestOverride(callInfo, model);
            return System.Threading.Tasks.Task.FromResult(callInfo as ActionResult);
        }

        [NonAction]
        partial void SuspendRequestOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.Guid gid);

        [NonAction]
        public override System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> SuspendRequest(System.Guid gid)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SuspendRequest);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "gid", gid);
            SuspendRequestOverride(callInfo, gid);
            return System.Threading.Tasks.Task.FromResult(callInfo as ActionResult);
        }

        [NonAction]
        partial void SetStatusPaidOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.Guid gid, string paymentMethod);

        [NonAction]
        public override System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> SetStatusPaid(System.Guid gid, string paymentMethod)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SetStatusPaid);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "gid", gid);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "paymentMethod", paymentMethod);
            SetStatusPaidOverride(callInfo, gid, paymentMethod);
            return System.Threading.Tasks.Task.FromResult(callInfo as ActionResult);
        }

        [NonAction]
        partial void PrintPaymentRequestsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, EPayments.Web.DataObjects.EserviceAdminRequestSearchDO searchDO, bool printAllResults);

        [NonAction]
        public override System.Web.Mvc.ActionResult PrintPaymentRequests(EPayments.Web.DataObjects.EserviceAdminRequestSearchDO searchDO, bool printAllResults)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PrintPaymentRequests);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchDO", searchDO);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "printAllResults", printAllResults);
            PrintPaymentRequestsOverride(callInfo, searchDO, printAllResults);
            return callInfo;
        }

        [NonAction]
        partial void TransactionListOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, EPayments.Web.DataObjects.TransactionListSearchDO searchDO);

        [NonAction]
        public override System.Web.Mvc.ActionResult TransactionList(EPayments.Web.DataObjects.TransactionListSearchDO searchDO)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.TransactionList);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchDO", searchDO);
            TransactionListOverride(callInfo, searchDO);
            return callInfo;
        }

        [NonAction]
        partial void TransactionListSearchOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, EPayments.Web.DataObjects.TransactionListSearchDO searchDO);

        [NonAction]
        public override System.Web.Mvc.ActionResult TransactionListSearch(EPayments.Web.DataObjects.TransactionListSearchDO searchDO)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.TransactionListSearch);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchDO", searchDO);
            TransactionListSearchOverride(callInfo, searchDO);
            return callInfo;
        }

        [NonAction]
        partial void TransactionListSortOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, EPayments.Web.DataObjects.TransactionListSearchDO searchDO);

        [NonAction]
        public override System.Web.Mvc.ActionResult TransactionListSort(EPayments.Web.DataObjects.TransactionListSearchDO searchDO)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.TransactionListSort);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchDO", searchDO);
            TransactionListSortOverride(callInfo, searchDO);
            return callInfo;
        }

        [NonAction]
        partial void TransactionDetailsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult TransactionDetails(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.TransactionDetails);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            TransactionDetailsOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void TransactionReferencedPaymentOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.Guid id, bool showDetailsForm);

        [NonAction]
        public override System.Web.Mvc.ActionResult TransactionReferencedPayment(System.Guid id, bool showDetailsForm)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.TransactionReferencedPayment);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "showDetailsForm", showDetailsForm);
            TransactionReferencedPaymentOverride(callInfo, id, showDetailsForm);
            return callInfo;
        }

        [NonAction]
        partial void PrintOrderOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.Guid id);

        [NonAction]
        public override System.Web.Mvc.ActionResult PrintOrder(System.Guid id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PrintOrder);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            PrintOrderOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void DownloadPdfOrderOverride(T4MVC_System_Web_Mvc_FileResult callInfo, System.Guid id);

        [NonAction]
        public override System.Web.Mvc.FileResult DownloadPdfOrder(System.Guid id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_FileResult(Area, Name, ActionNames.DownloadPdfOrder);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DownloadPdfOrderOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void EditSettingsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult EditSettings()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditSettings);
            EditSettingsOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void EditSettingsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, EPayments.Web.Models.EserviceAdmin.EditSettingsVM model);

        [NonAction]
        public override System.Web.Mvc.ActionResult EditSettings(EPayments.Web.Models.EserviceAdmin.EditSettingsVM model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditSettings);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            EditSettingsOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void SettingsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, EPayments.Web.DataObjects.RequestAccessListSearchDO searchDO);

        [NonAction]
        public override System.Web.Mvc.ActionResult Settings(EPayments.Web.DataObjects.RequestAccessListSearchDO searchDO)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Settings);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchDO", searchDO);
            SettingsOverride(callInfo, searchDO);
            return callInfo;
        }

        [NonAction]
        partial void TransactionListExportExcelOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, EPayments.Web.DataObjects.TransactionListSearchDO searchDO);

        [NonAction]
        public override System.Web.Mvc.ActionResult TransactionListExportExcel(EPayments.Web.DataObjects.TransactionListSearchDO searchDO)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.TransactionListExportExcel);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchDO", searchDO);
            TransactionListExportExcelOverride(callInfo, searchDO);
            return callInfo;
        }

        [NonAction]
        partial void TransactionListExportHtmlOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, EPayments.Web.DataObjects.TransactionListSearchDO searchDO);

        [NonAction]
        public override System.Web.Mvc.ActionResult TransactionListExportHtml(EPayments.Web.DataObjects.TransactionListSearchDO searchDO)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.TransactionListExportHtml);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchDO", searchDO);
            TransactionListExportHtmlOverride(callInfo, searchDO);
            return callInfo;
        }

        [NonAction]
        partial void TransactionListExportXmlOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, EPayments.Web.DataObjects.TransactionListSearchDO searchDO);

        [NonAction]
        public override System.Web.Mvc.ActionResult TransactionListExportXml(EPayments.Web.DataObjects.TransactionListSearchDO searchDO)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.TransactionListExportXml);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchDO", searchDO);
            TransactionListExportXmlOverride(callInfo, searchDO);
            return callInfo;
        }

        [NonAction]
        partial void TransactionListPrintHtmlOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, EPayments.Web.DataObjects.TransactionListSearchDO searchDO);

        [NonAction]
        public override System.Web.Mvc.ActionResult TransactionListPrintHtml(EPayments.Web.DataObjects.TransactionListSearchDO searchDO)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.TransactionListPrintHtml);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchDO", searchDO);
            TransactionListPrintHtmlOverride(callInfo, searchDO);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
