// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace EPayments.Web.Controllers
{
    public partial class PaymentController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected PaymentController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult List()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.List);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ListSearch()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ListSearch);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ListSort()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ListSort);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult PaymentRequestsExportAsPdf()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PaymentRequestsExportAsPdf);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult PaymentRequestsExportAsExcel()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PaymentRequestsExportAsExcel);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Order()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Order);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Details()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Details);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult CancelRequest()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CancelRequest);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult PrintOrder()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PrintOrder);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult PrintDetails()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PrintDetails);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.FileResult DownloadPdfOrder()
        {
            return new T4MVC_System_Web_Mvc_FileResult(Area, Name, ActionNames.DownloadPdfOrder);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.FileResult DownloadPdfDetails()
        {
            return new T4MVC_System_Web_Mvc_FileResult(Area, Name, ActionNames.DownloadPdfDetails);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult TaxAgreementDsk()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.TaxAgreementDsk);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult TaxAgreementCvpos()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.TaxAgreementCvpos);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult TaxAgreementCvposMultiple()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.TaxAgreementCvposMultiple);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult TaxAgreementBorica()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.TaxAgreementBorica);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult TaxAgreementFiBank()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.TaxAgreementFiBank);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult TaxAgreementEpay()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.TaxAgreementEpay);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Share()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Share);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GenerateAccessCode()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GenerateAccessCode);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public PaymentController Actions { get { return MVC.Payment; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Payment";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Payment";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string List = "List";
            public readonly string ListSearch = "ListSearch";
            public readonly string ListSort = "ListSort";
            public readonly string PaymentRequestsExportAsPdf = "PaymentRequestsExportAsPdf";
            public readonly string PaymentRequestsExportAsExcel = "PaymentRequestsExportAsExcel";
            public readonly string Order = "Order";
            public readonly string Details = "Details";
            public readonly string CancelRequest = "CancelRequest";
            public readonly string PrintOrder = "PrintOrder";
            public readonly string PrintDetails = "PrintDetails";
            public readonly string DownloadPdfOrder = "DownloadPdfOrder";
            public readonly string DownloadPdfDetails = "DownloadPdfDetails";
            public readonly string TaxAgreementDsk = "TaxAgreementDsk";
            public readonly string TaxAgreementCvpos = "TaxAgreementCvpos";
            public readonly string TaxAgreementCvposMultiple = "TaxAgreementCvposMultiple";
            public readonly string TaxAgreementBorica = "TaxAgreementBorica";
            public readonly string TaxAgreementFiBank = "TaxAgreementFiBank";
            public readonly string TaxAgreementEpay = "TaxAgreementEpay";
            public readonly string Share = "Share";
            public readonly string GenerateAccessCode = "GenerateAccessCode";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string List = "List";
            public const string ListSearch = "ListSearch";
            public const string ListSort = "ListSort";
            public const string PaymentRequestsExportAsPdf = "PaymentRequestsExportAsPdf";
            public const string PaymentRequestsExportAsExcel = "PaymentRequestsExportAsExcel";
            public const string Order = "Order";
            public const string Details = "Details";
            public const string CancelRequest = "CancelRequest";
            public const string PrintOrder = "PrintOrder";
            public const string PrintDetails = "PrintDetails";
            public const string DownloadPdfOrder = "DownloadPdfOrder";
            public const string DownloadPdfDetails = "DownloadPdfDetails";
            public const string TaxAgreementDsk = "TaxAgreementDsk";
            public const string TaxAgreementCvpos = "TaxAgreementCvpos";
            public const string TaxAgreementCvposMultiple = "TaxAgreementCvposMultiple";
            public const string TaxAgreementBorica = "TaxAgreementBorica";
            public const string TaxAgreementFiBank = "TaxAgreementFiBank";
            public const string TaxAgreementEpay = "TaxAgreementEpay";
            public const string Share = "Share";
            public const string GenerateAccessCode = "GenerateAccessCode";
        }


        static readonly ActionParamsClass_List s_params_List = new ActionParamsClass_List();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_List ListParams { get { return s_params_List; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_List
        {
            public readonly string searchDO = "searchDO";
        }
        static readonly ActionParamsClass_ListSearch s_params_ListSearch = new ActionParamsClass_ListSearch();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ListSearch ListSearchParams { get { return s_params_ListSearch; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ListSearch
        {
            public readonly string searchDO = "searchDO";
        }
        static readonly ActionParamsClass_ListSort s_params_ListSort = new ActionParamsClass_ListSort();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ListSort ListSortParams { get { return s_params_ListSort; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ListSort
        {
            public readonly string searchDO = "searchDO";
        }
        static readonly ActionParamsClass_PaymentRequestsExportAsPdf s_params_PaymentRequestsExportAsPdf = new ActionParamsClass_PaymentRequestsExportAsPdf();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PaymentRequestsExportAsPdf PaymentRequestsExportAsPdfParams { get { return s_params_PaymentRequestsExportAsPdf; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PaymentRequestsExportAsPdf
        {
            public readonly string searchDO = "searchDO";
        }
        static readonly ActionParamsClass_PaymentRequestsExportAsExcel s_params_PaymentRequestsExportAsExcel = new ActionParamsClass_PaymentRequestsExportAsExcel();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PaymentRequestsExportAsExcel PaymentRequestsExportAsExcelParams { get { return s_params_PaymentRequestsExportAsExcel; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PaymentRequestsExportAsExcel
        {
            public readonly string searchDO = "searchDO";
        }
        static readonly ActionParamsClass_Order s_params_Order = new ActionParamsClass_Order();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Order OrderParams { get { return s_params_Order; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Order
        {
            public readonly string id = "id";
            public readonly string showDetailsForm = "showDetailsForm";
        }
        static readonly ActionParamsClass_Details s_params_Details = new ActionParamsClass_Details();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Details DetailsParams { get { return s_params_Details; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Details
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_CancelRequest s_params_CancelRequest = new ActionParamsClass_CancelRequest();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CancelRequest CancelRequestParams { get { return s_params_CancelRequest; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CancelRequest
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_PrintOrder s_params_PrintOrder = new ActionParamsClass_PrintOrder();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PrintOrder PrintOrderParams { get { return s_params_PrintOrder; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PrintOrder
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_PrintDetails s_params_PrintDetails = new ActionParamsClass_PrintDetails();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PrintDetails PrintDetailsParams { get { return s_params_PrintDetails; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PrintDetails
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_DownloadPdfOrder s_params_DownloadPdfOrder = new ActionParamsClass_DownloadPdfOrder();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DownloadPdfOrder DownloadPdfOrderParams { get { return s_params_DownloadPdfOrder; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DownloadPdfOrder
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_DownloadPdfDetails s_params_DownloadPdfDetails = new ActionParamsClass_DownloadPdfDetails();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DownloadPdfDetails DownloadPdfDetailsParams { get { return s_params_DownloadPdfDetails; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DownloadPdfDetails
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_TaxAgreementDsk s_params_TaxAgreementDsk = new ActionParamsClass_TaxAgreementDsk();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_TaxAgreementDsk TaxAgreementDskParams { get { return s_params_TaxAgreementDsk; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_TaxAgreementDsk
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_TaxAgreementCvpos s_params_TaxAgreementCvpos = new ActionParamsClass_TaxAgreementCvpos();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_TaxAgreementCvpos TaxAgreementCvposParams { get { return s_params_TaxAgreementCvpos; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_TaxAgreementCvpos
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_TaxAgreementCvposMultiple s_params_TaxAgreementCvposMultiple = new ActionParamsClass_TaxAgreementCvposMultiple();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_TaxAgreementCvposMultiple TaxAgreementCvposMultipleParams { get { return s_params_TaxAgreementCvposMultiple; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_TaxAgreementCvposMultiple
        {
            public readonly string gids = "gids";
        }
        static readonly ActionParamsClass_TaxAgreementBorica s_params_TaxAgreementBorica = new ActionParamsClass_TaxAgreementBorica();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_TaxAgreementBorica TaxAgreementBoricaParams { get { return s_params_TaxAgreementBorica; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_TaxAgreementBorica
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_TaxAgreementFiBank s_params_TaxAgreementFiBank = new ActionParamsClass_TaxAgreementFiBank();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_TaxAgreementFiBank TaxAgreementFiBankParams { get { return s_params_TaxAgreementFiBank; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_TaxAgreementFiBank
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_TaxAgreementEpay s_params_TaxAgreementEpay = new ActionParamsClass_TaxAgreementEpay();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_TaxAgreementEpay TaxAgreementEpayParams { get { return s_params_TaxAgreementEpay; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_TaxAgreementEpay
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_Share s_params_Share = new ActionParamsClass_Share();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Share ShareParams { get { return s_params_Share; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Share
        {
            public readonly string id = "id";
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_GenerateAccessCode s_params_GenerateAccessCode = new ActionParamsClass_GenerateAccessCode();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GenerateAccessCode GenerateAccessCodeParams { get { return s_params_GenerateAccessCode; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GenerateAccessCode
        {
            public readonly string id = "id";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Details = "Details";
                public readonly string DetailsPrint = "DetailsPrint";
                public readonly string List = "List";
                public readonly string Share = "Share";
            }
            public readonly string Details = "~/Views/Payment/Details.cshtml";
            public readonly string DetailsPrint = "~/Views/Payment/DetailsPrint.cshtml";
            public readonly string List = "~/Views/Payment/List.cshtml";
            public readonly string Share = "~/Views/Payment/Share.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_PaymentController : EPayments.Web.Controllers.PaymentController
    {
        public T4MVC_PaymentController() : base(Dummy.Instance) { }

        [NonAction]
        partial void ListOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, EPayments.Web.DataObjects.ListSearchDO searchDO);

        [NonAction]
        public override System.Web.Mvc.ActionResult List(EPayments.Web.DataObjects.ListSearchDO searchDO)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.List);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchDO", searchDO);
            ListOverride(callInfo, searchDO);
            return callInfo;
        }

        [NonAction]
        partial void ListSearchOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, EPayments.Web.DataObjects.ListSearchDO searchDO);

        [NonAction]
        public override System.Web.Mvc.ActionResult ListSearch(EPayments.Web.DataObjects.ListSearchDO searchDO)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ListSearch);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchDO", searchDO);
            ListSearchOverride(callInfo, searchDO);
            return callInfo;
        }

        [NonAction]
        partial void ListSortOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, EPayments.Web.DataObjects.ListSearchDO searchDO);

        [NonAction]
        public override System.Web.Mvc.ActionResult ListSort(EPayments.Web.DataObjects.ListSearchDO searchDO)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ListSort);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchDO", searchDO);
            ListSortOverride(callInfo, searchDO);
            return callInfo;
        }

        [NonAction]
        partial void PaymentRequestsExportAsPdfOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, EPayments.Web.DataObjects.ListSearchDO searchDO);

        [NonAction]
        public override System.Web.Mvc.ActionResult PaymentRequestsExportAsPdf(EPayments.Web.DataObjects.ListSearchDO searchDO)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PaymentRequestsExportAsPdf);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchDO", searchDO);
            PaymentRequestsExportAsPdfOverride(callInfo, searchDO);
            return callInfo;
        }

        [NonAction]
        partial void PaymentRequestsExportAsExcelOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, EPayments.Web.DataObjects.ListSearchDO searchDO);

        [NonAction]
        public override System.Web.Mvc.ActionResult PaymentRequestsExportAsExcel(EPayments.Web.DataObjects.ListSearchDO searchDO)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PaymentRequestsExportAsExcel);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchDO", searchDO);
            PaymentRequestsExportAsExcelOverride(callInfo, searchDO);
            return callInfo;
        }

        [NonAction]
        partial void OrderOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.Guid id, bool showDetailsForm);

        [NonAction]
        public override System.Web.Mvc.ActionResult Order(System.Guid id, bool showDetailsForm)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Order);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "showDetailsForm", showDetailsForm);
            OrderOverride(callInfo, id, showDetailsForm);
            return callInfo;
        }

        [NonAction]
        partial void DetailsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.Guid id);

        [NonAction]
        public override System.Web.Mvc.ActionResult Details(System.Guid id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Details);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DetailsOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void CancelRequestOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.Guid id);

        [NonAction]
        public override System.Web.Mvc.ActionResult CancelRequest(System.Guid id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CancelRequest);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            CancelRequestOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void PrintOrderOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.Guid id);

        [NonAction]
        public override System.Web.Mvc.ActionResult PrintOrder(System.Guid id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PrintOrder);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            PrintOrderOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void PrintDetailsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.Guid id);

        [NonAction]
        public override System.Web.Mvc.ActionResult PrintDetails(System.Guid id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PrintDetails);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            PrintDetailsOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void DownloadPdfOrderOverride(T4MVC_System_Web_Mvc_FileResult callInfo, System.Guid id);

        [NonAction]
        public override System.Web.Mvc.FileResult DownloadPdfOrder(System.Guid id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_FileResult(Area, Name, ActionNames.DownloadPdfOrder);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DownloadPdfOrderOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void DownloadPdfDetailsOverride(T4MVC_System_Web_Mvc_FileResult callInfo, System.Guid id);

        [NonAction]
        public override System.Web.Mvc.FileResult DownloadPdfDetails(System.Guid id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_FileResult(Area, Name, ActionNames.DownloadPdfDetails);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DownloadPdfDetailsOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void TaxAgreementDskOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.Guid id);

        [NonAction]
        public override System.Web.Mvc.ActionResult TaxAgreementDsk(System.Guid id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.TaxAgreementDsk);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            TaxAgreementDskOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void TaxAgreementCvposOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.Guid id);

        [NonAction]
        public override System.Web.Mvc.ActionResult TaxAgreementCvpos(System.Guid id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.TaxAgreementCvpos);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            TaxAgreementCvposOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void TaxAgreementCvposMultipleOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.Guid[] gids);

        [NonAction]
        public override System.Web.Mvc.ActionResult TaxAgreementCvposMultiple(System.Guid[] gids)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.TaxAgreementCvposMultiple);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "gids", gids);
            TaxAgreementCvposMultipleOverride(callInfo, gids);
            return callInfo;
        }

        [NonAction]
        partial void TaxAgreementBoricaOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.Guid id);

        [NonAction]
        public override System.Web.Mvc.ActionResult TaxAgreementBorica(System.Guid id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.TaxAgreementBorica);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            TaxAgreementBoricaOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void TaxAgreementFiBankOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.Guid id);

        [NonAction]
        public override System.Web.Mvc.ActionResult TaxAgreementFiBank(System.Guid id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.TaxAgreementFiBank);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            TaxAgreementFiBankOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void TaxAgreementEpayOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.Guid id);

        [NonAction]
        public override System.Web.Mvc.ActionResult TaxAgreementEpay(System.Guid id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.TaxAgreementEpay);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            TaxAgreementEpayOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void ShareOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.Guid id);

        [NonAction]
        public override System.Web.Mvc.ActionResult Share(System.Guid id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Share);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ShareOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void ShareOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, EPayments.Web.Models.Payments.ShareVM model);

        [NonAction]
        public override System.Web.Mvc.ActionResult Share(EPayments.Web.Models.Payments.ShareVM model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Share);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            ShareOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void GenerateAccessCodeOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.Guid id);

        [NonAction]
        public override System.Web.Mvc.ActionResult GenerateAccessCode(System.Guid id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GenerateAccessCode);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            GenerateAccessCodeOverride(callInfo, id);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
