// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace T4MVC
{
    public class SharedController
    {

        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _AutoPost = "_AutoPost";
                public readonly string _AutoPostBoricaVpos = "_AutoPostBoricaVpos";
                public readonly string _EidSubmitForm = "_EidSubmitForm";
                public readonly string _EmptyLayout = "_EmptyLayout";
                public readonly string _Error = "_Error";
                public readonly string _Layout = "_Layout";
                public readonly string _Order = "_Order";
                public readonly string _OrderPrint = "_OrderPrint";
                public readonly string _Paging = "_Paging";
                public readonly string _PaymentRequestsPrintPdf = "_PaymentRequestsPrintPdf";
                public readonly string _PrintHtml = "_PrintHtml";
                public readonly string _PrintPdf = "_PrintPdf";
                public readonly string _TaxAgreementBorica = "_TaxAgreementBorica";
                public readonly string _TaxAgreementBoricaCvpos = "_TaxAgreementBoricaCvpos";
                public readonly string _TaxAgreementDsk = "_TaxAgreementDsk";
                public readonly string _TaxAgreementEpay = "_TaxAgreementEpay";
                public readonly string _TaxAgreementFiBank = "_TaxAgreementFiBank";
                public readonly string _UserPaymentRequestsPrintPdf = "_UserPaymentRequestsPrintPdf";
                public readonly string _VposPaymentSumulation = "_VposPaymentSumulation";
            }
            public readonly string _AutoPost = "~/Views/Shared/_AutoPost.cshtml";
            public readonly string _AutoPostBoricaVpos = "~/Views/Shared/_AutoPostBoricaVpos.cshtml";
            public readonly string _EidSubmitForm = "~/Views/Shared/_EidSubmitForm.cshtml";
            public readonly string _EmptyLayout = "~/Views/Shared/_EmptyLayout.cshtml";
            public readonly string _Error = "~/Views/Shared/_Error.cshtml";
            public readonly string _Layout = "~/Views/Shared/_Layout.cshtml";
            public readonly string _Order = "~/Views/Shared/_Order.cshtml";
            public readonly string _OrderPrint = "~/Views/Shared/_OrderPrint.cshtml";
            public readonly string _Paging = "~/Views/Shared/_Paging.cshtml";
            public readonly string _PaymentRequestsPrintPdf = "~/Views/Shared/_PaymentRequestsPrintPdf.cshtml";
            public readonly string _PrintHtml = "~/Views/Shared/_PrintHtml.cshtml";
            public readonly string _PrintPdf = "~/Views/Shared/_PrintPdf.cshtml";
            public readonly string _TaxAgreementBorica = "~/Views/Shared/_TaxAgreementBorica.cshtml";
            public readonly string _TaxAgreementBoricaCvpos = "~/Views/Shared/_TaxAgreementBoricaCvpos.cshtml";
            public readonly string _TaxAgreementDsk = "~/Views/Shared/_TaxAgreementDsk.cshtml";
            public readonly string _TaxAgreementEpay = "~/Views/Shared/_TaxAgreementEpay.cshtml";
            public readonly string _TaxAgreementFiBank = "~/Views/Shared/_TaxAgreementFiBank.cshtml";
            public readonly string _UserPaymentRequestsPrintPdf = "~/Views/Shared/_UserPaymentRequestsPrintPdf.cshtml";
            public readonly string _VposPaymentSumulation = "~/Views/Shared/_VposPaymentSumulation.cshtml";
        }
    }

}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
