// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace EPayments.Web.Controllers
{
    public partial class VposController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected VposController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult TestEserviceClientVpos()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.TestEserviceClientVpos);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Payment()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Payment);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult PaymentViaEpay()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PaymentViaEpay);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult PaymentConfirmed()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PaymentConfirmed);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult PaymentCanceled()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PaymentCanceled);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DskPayment()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DskPayment);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DskSuccessfulPayment()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DskSuccessfulPayment);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DskFailedPayment()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DskFailedPayment);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SimulateVposPayment()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SimulateVposPayment);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult BoricaPayment_()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.BoricaPayment_);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult BoricaPayment()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.BoricaPayment);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult FiBankPayment()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.FiBankPayment);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult FiBankPostResult()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.FiBankPostResult);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult EpayPayment()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EpayPayment);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult EpayCheckResult()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EpayCheckResult);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DskEcommPaymentResult()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DskEcommPaymentResult);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Borica()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Borica);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult BoricaBackref()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.BoricaBackref);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public VposController Actions { get { return MVC.Vpos; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Vpos";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Vpos";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string TestEserviceClientVpos = "TestEserviceClientVpos";
            public readonly string Payment = "Payment";
            public readonly string PaymentViaEpay = "PaymentViaEpay";
            public readonly string PaymentConfirmed = "PaymentConfirmed";
            public readonly string PaymentCanceled = "PaymentCanceled";
            public readonly string DskPayment = "DskPayment";
            public readonly string DskSuccessfulPayment = "DskSuccessfulPayment";
            public readonly string DskFailedPayment = "DskFailedPayment";
            public readonly string SimulateVposPayment = "SimulateVposPayment";
            public readonly string BoricaPayment_ = "BoricaPayment_";
            public readonly string BoricaPayment = "BoricaPayment";
            public readonly string FiBankPayment = "FiBankPayment";
            public readonly string FiBankPostResult = "FiBankPostResult";
            public readonly string EpayPayment = "EpayPayment";
            public readonly string EpayCheckResult = "EpayCheckResult";
            public readonly string DskEcommPaymentResult = "DskEcommPaymentResult";
            public readonly string Borica = "Borica";
            public readonly string BoricaBackref = "BoricaBackref";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string TestEserviceClientVpos = "TestEserviceClientVpos";
            public const string Payment = "Payment";
            public const string PaymentViaEpay = "PaymentViaEpay";
            public const string PaymentConfirmed = "PaymentConfirmed";
            public const string PaymentCanceled = "PaymentCanceled";
            public const string DskPayment = "DskPayment";
            public const string DskSuccessfulPayment = "DskSuccessfulPayment";
            public const string DskFailedPayment = "DskFailedPayment";
            public const string SimulateVposPayment = "SimulateVposPayment";
            public const string BoricaPayment_ = "BoricaPayment_";
            public const string BoricaPayment = "BoricaPayment";
            public const string FiBankPayment = "FiBankPayment";
            public const string FiBankPostResult = "FiBankPostResult";
            public const string EpayPayment = "EpayPayment";
            public const string EpayCheckResult = "EpayCheckResult";
            public const string DskEcommPaymentResult = "DskEcommPaymentResult";
            public const string Borica = "Borica";
            public const string BoricaBackref = "BoricaBackref";
        }


        static readonly ActionParamsClass_TestEserviceClientVpos s_params_TestEserviceClientVpos = new ActionParamsClass_TestEserviceClientVpos();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_TestEserviceClientVpos TestEserviceClientVposParams { get { return s_params_TestEserviceClientVpos; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_TestEserviceClientVpos
        {
            public readonly string requestDO = "requestDO";
        }
        static readonly ActionParamsClass_Payment s_params_Payment = new ActionParamsClass_Payment();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Payment PaymentParams { get { return s_params_Payment; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Payment
        {
            public readonly string requestDO = "requestDO";
        }
        static readonly ActionParamsClass_PaymentViaEpay s_params_PaymentViaEpay = new ActionParamsClass_PaymentViaEpay();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PaymentViaEpay PaymentViaEpayParams { get { return s_params_PaymentViaEpay; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PaymentViaEpay
        {
            public readonly string requestDO = "requestDO";
        }
        static readonly ActionParamsClass_PaymentConfirmed s_params_PaymentConfirmed = new ActionParamsClass_PaymentConfirmed();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PaymentConfirmed PaymentConfirmedParams { get { return s_params_PaymentConfirmed; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PaymentConfirmed
        {
            public readonly string requestDO = "requestDO";
            public readonly string isEpayPayment = "isEpayPayment";
        }
        static readonly ActionParamsClass_PaymentCanceled s_params_PaymentCanceled = new ActionParamsClass_PaymentCanceled();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PaymentCanceled PaymentCanceledParams { get { return s_params_PaymentCanceled; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PaymentCanceled
        {
            public readonly string requestDO = "requestDO";
        }
        static readonly ActionParamsClass_DskPayment s_params_DskPayment = new ActionParamsClass_DskPayment();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DskPayment DskPaymentParams { get { return s_params_DskPayment; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DskPayment
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_DskSuccessfulPayment s_params_DskSuccessfulPayment = new ActionParamsClass_DskSuccessfulPayment();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DskSuccessfulPayment DskSuccessfulPaymentParams { get { return s_params_DskSuccessfulPayment; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DskSuccessfulPayment
        {
            public readonly string gid = "gid";
            public readonly string vposRedirectGid = "vposRedirectGid";
            public readonly string resultDO = "resultDO";
        }
        static readonly ActionParamsClass_DskFailedPayment s_params_DskFailedPayment = new ActionParamsClass_DskFailedPayment();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DskFailedPayment DskFailedPaymentParams { get { return s_params_DskFailedPayment; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DskFailedPayment
        {
            public readonly string gid = "gid";
            public readonly string vposRedirectGid = "vposRedirectGid";
            public readonly string resultDO = "resultDO";
        }
        static readonly ActionParamsClass_SimulateVposPayment s_params_SimulateVposPayment = new ActionParamsClass_SimulateVposPayment();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SimulateVposPayment SimulateVposPaymentParams { get { return s_params_SimulateVposPayment; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SimulateVposPayment
        {
            public readonly string gid = "gid";
            public readonly string vposRedirectGid = "vposRedirectGid";
            public readonly string paymentRequestIdentifier = "paymentRequestIdentifier";
            public readonly string success = "success";
        }
        static readonly ActionParamsClass_BoricaPayment_ s_params_BoricaPayment_ = new ActionParamsClass_BoricaPayment_();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_BoricaPayment_ BoricaPayment_Params { get { return s_params_BoricaPayment_; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_BoricaPayment_
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_BoricaPayment s_params_BoricaPayment = new ActionParamsClass_BoricaPayment();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_BoricaPayment BoricaPaymentParams { get { return s_params_BoricaPayment; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_BoricaPayment
        {
            public readonly string apgwResponse = "apgwResponse";
        }
        static readonly ActionParamsClass_FiBankPayment s_params_FiBankPayment = new ActionParamsClass_FiBankPayment();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_FiBankPayment FiBankPaymentParams { get { return s_params_FiBankPayment; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_FiBankPayment
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_FiBankPostResult s_params_FiBankPostResult = new ActionParamsClass_FiBankPostResult();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_FiBankPostResult FiBankPostResultParams { get { return s_params_FiBankPostResult; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_FiBankPostResult
        {
            public readonly string trans_id = "trans_id";
            public readonly string ucaf_Cardholder_Confirm = "ucaf_Cardholder_Confirm";
        }
        static readonly ActionParamsClass_EpayPayment s_params_EpayPayment = new ActionParamsClass_EpayPayment();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_EpayPayment EpayPaymentParams { get { return s_params_EpayPayment; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_EpayPayment
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_EpayCheckResult s_params_EpayCheckResult = new ActionParamsClass_EpayCheckResult();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_EpayCheckResult EpayCheckResultParams { get { return s_params_EpayCheckResult; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_EpayCheckResult
        {
            public readonly string res = "res";
            public readonly string ino = "ino";
        }
        static readonly ActionParamsClass_DskEcommPaymentResult s_params_DskEcommPaymentResult = new ActionParamsClass_DskEcommPaymentResult();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DskEcommPaymentResult DskEcommPaymentResultParams { get { return s_params_DskEcommPaymentResult; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DskEcommPaymentResult
        {
            public readonly string orderId = "orderId";
        }
        static readonly ActionParamsClass_Borica s_params_Borica = new ActionParamsClass_Borica();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Borica BoricaParams { get { return s_params_Borica; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Borica
        {
            public readonly string gids = "gids";
        }
        static readonly ActionParamsClass_BoricaBackref s_params_BoricaBackref = new ActionParamsClass_BoricaBackref();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_BoricaBackref BoricaBackrefParams { get { return s_params_BoricaBackref; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_BoricaBackref
        {
            public readonly string apgwResponse = "apgwResponse";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
            }
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_VposController : EPayments.Web.Controllers.VposController
    {
        public T4MVC_VposController() : base(Dummy.Instance) { }

        [NonAction]
        partial void TestEserviceClientVposOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, EPayments.Common.DataObjects.AuthRequestDO requestDO);

        [NonAction]
        public override System.Web.Mvc.ActionResult TestEserviceClientVpos(EPayments.Common.DataObjects.AuthRequestDO requestDO)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.TestEserviceClientVpos);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "requestDO", requestDO);
            TestEserviceClientVposOverride(callInfo, requestDO);
            return callInfo;
        }

        [NonAction]
        partial void PaymentOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, EPayments.Common.DataObjects.AuthRequestDO requestDO);

        [NonAction]
        public override System.Web.Mvc.ActionResult Payment(EPayments.Common.DataObjects.AuthRequestDO requestDO)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Payment);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "requestDO", requestDO);
            PaymentOverride(callInfo, requestDO);
            return callInfo;
        }

        [NonAction]
        partial void PaymentViaEpayOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, EPayments.Common.DataObjects.AuthRequestDO requestDO);

        [NonAction]
        public override System.Web.Mvc.ActionResult PaymentViaEpay(EPayments.Common.DataObjects.AuthRequestDO requestDO)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PaymentViaEpay);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "requestDO", requestDO);
            PaymentViaEpayOverride(callInfo, requestDO);
            return callInfo;
        }

        [NonAction]
        partial void PaymentConfirmedOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, EPayments.Common.DataObjects.AuthRequestDO requestDO, bool? isEpayPayment);

        [NonAction]
        public override System.Web.Mvc.ActionResult PaymentConfirmed(EPayments.Common.DataObjects.AuthRequestDO requestDO, bool? isEpayPayment)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PaymentConfirmed);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "requestDO", requestDO);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "isEpayPayment", isEpayPayment);
            PaymentConfirmedOverride(callInfo, requestDO, isEpayPayment);
            return callInfo;
        }

        [NonAction]
        partial void PaymentCanceledOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, EPayments.Common.DataObjects.AuthRequestDO requestDO);

        [NonAction]
        public override System.Web.Mvc.ActionResult PaymentCanceled(EPayments.Common.DataObjects.AuthRequestDO requestDO)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PaymentCanceled);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "requestDO", requestDO);
            PaymentCanceledOverride(callInfo, requestDO);
            return callInfo;
        }

        [NonAction]
        partial void DskPaymentOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.Guid id);

        [NonAction]
        public override System.Web.Mvc.ActionResult DskPayment(System.Guid id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DskPayment);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DskPaymentOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void DskSuccessfulPaymentOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.Guid gid, System.Guid? vposRedirectGid, EPayments.Web.VposHelpers.Dsk.DskVposResultDO resultDO);

        [NonAction]
        public override System.Web.Mvc.ActionResult DskSuccessfulPayment(System.Guid gid, System.Guid? vposRedirectGid, EPayments.Web.VposHelpers.Dsk.DskVposResultDO resultDO)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DskSuccessfulPayment);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "gid", gid);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "vposRedirectGid", vposRedirectGid);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "resultDO", resultDO);
            DskSuccessfulPaymentOverride(callInfo, gid, vposRedirectGid, resultDO);
            return callInfo;
        }

        [NonAction]
        partial void DskFailedPaymentOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.Guid gid, System.Guid? vposRedirectGid, EPayments.Web.VposHelpers.Dsk.DskVposResultDO resultDO);

        [NonAction]
        public override System.Web.Mvc.ActionResult DskFailedPayment(System.Guid gid, System.Guid? vposRedirectGid, EPayments.Web.VposHelpers.Dsk.DskVposResultDO resultDO)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DskFailedPayment);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "gid", gid);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "vposRedirectGid", vposRedirectGid);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "resultDO", resultDO);
            DskFailedPaymentOverride(callInfo, gid, vposRedirectGid, resultDO);
            return callInfo;
        }

        [NonAction]
        partial void SimulateVposPaymentOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.Guid gid, System.Guid? vposRedirectGid, string paymentRequestIdentifier, bool success);

        [NonAction]
        public override System.Web.Mvc.ActionResult SimulateVposPayment(System.Guid gid, System.Guid? vposRedirectGid, string paymentRequestIdentifier, bool success)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SimulateVposPayment);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "gid", gid);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "vposRedirectGid", vposRedirectGid);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "paymentRequestIdentifier", paymentRequestIdentifier);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "success", success);
            SimulateVposPaymentOverride(callInfo, gid, vposRedirectGid, paymentRequestIdentifier, success);
            return callInfo;
        }

        [NonAction]
        partial void BoricaPayment_Override(T4MVC_System_Web_Mvc_ActionResult callInfo, System.Guid id);

        [NonAction]
        public override System.Web.Mvc.ActionResult BoricaPayment_(System.Guid id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.BoricaPayment_);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            BoricaPayment_Override(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void BoricaPaymentOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, EPayments.Data.ViewObjects.Web.APGModels.APGWPaymentResponseDataDO apgwResponse);

        [NonAction]
        public override System.Web.Mvc.ActionResult BoricaPayment(EPayments.Data.ViewObjects.Web.APGModels.APGWPaymentResponseDataDO apgwResponse)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.BoricaPayment);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "apgwResponse", apgwResponse);
            BoricaPaymentOverride(callInfo, apgwResponse);
            return callInfo;
        }

        [NonAction]
        partial void FiBankPaymentOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.Guid id);

        [NonAction]
        public override System.Web.Mvc.ActionResult FiBankPayment(System.Guid id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.FiBankPayment);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            FiBankPaymentOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void FiBankPostResultOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string trans_id, string ucaf_Cardholder_Confirm);

        [NonAction]
        public override System.Web.Mvc.ActionResult FiBankPostResult(string trans_id, string ucaf_Cardholder_Confirm)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.FiBankPostResult);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "trans_id", trans_id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "ucaf_Cardholder_Confirm", ucaf_Cardholder_Confirm);
            FiBankPostResultOverride(callInfo, trans_id, ucaf_Cardholder_Confirm);
            return callInfo;
        }

        [NonAction]
        partial void EpayPaymentOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.Guid id);

        [NonAction]
        public override System.Web.Mvc.ActionResult EpayPayment(System.Guid id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EpayPayment);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            EpayPaymentOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void EpayCheckResultOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string res, string ino);

        [NonAction]
        public override System.Web.Mvc.ActionResult EpayCheckResult(string res, string ino)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EpayCheckResult);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "res", res);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "ino", ino);
            EpayCheckResultOverride(callInfo, res, ino);
            return callInfo;
        }

        [NonAction]
        partial void DskEcommPaymentResultOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string orderId);

        [NonAction]
        public override System.Web.Mvc.ActionResult DskEcommPaymentResult(string orderId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DskEcommPaymentResult);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "orderId", orderId);
            DskEcommPaymentResultOverride(callInfo, orderId);
            return callInfo;
        }

        [NonAction]
        partial void BoricaOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.Guid[] gids);

        [NonAction]
        public override System.Web.Mvc.ActionResult Borica(System.Guid[] gids)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Borica);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "gids", gids);
            BoricaOverride(callInfo, gids);
            return callInfo;
        }

        [NonAction]
        partial void BoricaBackrefOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, EPayments.Data.ViewObjects.Web.APGModels.APGWPaymentResponseDataDO apgwResponse);

        [NonAction]
        public override System.Web.Mvc.ActionResult BoricaBackref(EPayments.Data.ViewObjects.Web.APGModels.APGWPaymentResponseDataDO apgwResponse)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.BoricaBackref);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "apgwResponse", apgwResponse);
            BoricaBackrefOverride(callInfo, apgwResponse);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
