CREATE TABLE [dbo].[AuthPassLogins](
	[AuthPassLoginId] [int] IDENTITY(1,1) NOT NULL,
	[Gid] [uniqueidentifier] NOT NULL,
	[IP] [nvarchar](50) NULL,
	[PostData] [nvarchar](max) NOT NULL,
	[LogDate] [datetime] NOT NULL,
 CONSTRAINT [PK_AuthPassLogins] PRIMARY KEY CLUSTERED 
(
	[AuthPassLoginId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Gid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]