//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPayments.EventRegister.EventRegisterService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://egov.bg/bes/ws/v1", ConfigurationName="EventRegisterService.RegisterEventSOAPPort")]
    public interface RegisterEventSOAPPort {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://egov.bg/bes/ws/auditlog/v1) of message RegisterEvent does not match the default value (http://egov.bg/bes/ws/v1)
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EventType))]
        void RegisterEvent(EPayments.EventRegister.EventRegisterService.RegisterEvent request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="")]
        System.Threading.Tasks.Task RegisterEventAsync(EPayments.EventRegister.EventRegisterService.RegisterEvent request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/bes/ws/auditlog/v1")]
    public partial class EAServiceLCEventType : EventType {
        
        private string authnReqIDField;
        
        private string authnRespIDField;
        
        private string documentRegIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string AuthnReqID {
            get {
                return this.authnReqIDField;
            }
            set {
                this.authnReqIDField = value;
                this.RaisePropertyChanged("AuthnReqID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string AuthnRespID {
            get {
                return this.authnRespIDField;
            }
            set {
                this.authnRespIDField = value;
                this.RaisePropertyChanged("AuthnRespID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string DocumentRegId {
            get {
                return this.documentRegIdField;
            }
            set {
                this.documentRegIdField = value;
                this.RaisePropertyChanged("DocumentRegId");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PersonalDataAccessAttemptType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EAServiceLCEventType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/bes/ws/auditlog/v1")]
    public partial class EventType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private bool idFieldSpecified;
        
        private System.DateTime eventTimeField;
        
        private EventTypeEnum eventType1Field;
        
        private string eventType2Field;
        
        private RequestedServiceType requestedServiceField;
        
        private string informationSystemOIDField;
        
        private string eventDescriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime EventTime {
            get {
                return this.eventTimeField;
            }
            set {
                this.eventTimeField = value;
                this.RaisePropertyChanged("EventTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EventType", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public EventTypeEnum EventType1 {
            get {
                return this.eventType1Field;
            }
            set {
                this.eventType1Field = value;
                this.RaisePropertyChanged("EventType1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string EventType2 {
            get {
                return this.eventType2Field;
            }
            set {
                this.eventType2Field = value;
                this.RaisePropertyChanged("EventType2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public RequestedServiceType RequestedService {
            get {
                return this.requestedServiceField;
            }
            set {
                this.requestedServiceField = value;
                this.RaisePropertyChanged("RequestedService");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string InformationSystemOID {
            get {
                return this.informationSystemOIDField;
            }
            set {
                this.informationSystemOIDField = value;
                this.RaisePropertyChanged("InformationSystemOID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string EventDescription {
            get {
                return this.eventDescriptionField;
            }
            set {
                this.eventDescriptionField = value;
                this.RaisePropertyChanged("EventDescription");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/bes/ws/auditlog/v1")]
    public enum EventTypeEnum {
        
        /// <remarks/>
        ROID_OID_CREATED,
        
        /// <remarks/>
        ROID_OID_UPDATED,
        
        /// <remarks/>
        ROID_OID_DELETED,
        
        /// <remarks/>
        RRES_ADMINISTRATION_CREATED,
        
        /// <remarks/>
        RRES_ADMINISTRATION_UPDATED,
        
        /// <remarks/>
        RRES_ADMINISTRATION_DELETED,
        
        /// <remarks/>
        RRES_IS_CREATED,
        
        /// <remarks/>
        RRES_IS_UPDATED,
        
        /// <remarks/>
        RRES_IS_DELETED,
        
        /// <remarks/>
        RRES_SERVICE_CREATED,
        
        /// <remarks/>
        RRES_SERVICE_UPDATED,
        
        /// <remarks/>
        RRES_SERVICE_DELETED,
        
        /// <remarks/>
        PERSONAL_DATA_ACCESS_ATTEMPT,
        
        /// <remarks/>
        PORTAL_ESERVICE_REQUESTED,
        
        /// <remarks/>
        PORTAL_AUTHN_REQUEST_SENT,
        
        /// <remarks/>
        PORTAL_AUTHN_RESPONSE_REDIRECTED,
        
        /// <remarks/>
        AUTHN_DENIED,
        
        /// <remarks/>
        AUTHN_ATTRBQUERY_SENT,
        
        /// <remarks/>
        AUTHN_ATTR_RECEIVED,
        
        /// <remarks/>
        AUTHN_RESPONSE_SENT,
        
        /// <remarks/>
        AUTHN_REQUEST_RECEIVED,
        
        /// <remarks/>
        AUTHN_SUCESSFUL,
        
        /// <remarks/>
        AUTHOR_REQUEST_SENT,
        
        /// <remarks/>
        AUTHOR_DENIED,
        
        /// <remarks/>
        AUTHOR_SUCCEEDED,
        
        /// <remarks/>
        AIS_AUTHN_RECEIVED,
        
        /// <remarks/>
        AIS_ESERVICE_VALIDATION_FAILED,
        
        /// <remarks/>
        AIS_ESERVICE_VALIDATION_SUCCEEDED,
        
        /// <remarks/>
        AIS_EPAYMENT_REQUEST_SENT,
        
        /// <remarks/>
        AIS_ESERVICE_DENIED,
        
        /// <remarks/>
        AIS_ESERVICE_STARTED,
        
        /// <remarks/>
        AIS_ESERVICE_RESULT_READY,
        
        /// <remarks/>
        AIS_ESERVICE_RESULT_REGISTRATION_SENT,
        
        /// <remarks/>
        AIS_ESERVICE_DOCUMENT_REGISTERED,
        
        /// <remarks/>
        AIS_ESERVICE_CANCELED_BY_USER,
        
        /// <remarks/>
        EPAYMENT_PAYMENT_REQUEST_RECEIVED,
        
        /// <remarks/>
        EPAYMENT_PAYMENT_REQUEST_DENIED,
        
        /// <remarks/>
        EPAYMENT_PAYMENT_VPOS_AUTHORIZED,
        
        /// <remarks/>
        EPAYMENT_PAYMENT_ORDERED,
        
        /// <remarks/>
        EPAYMENT_PAYMENT_PAID,
        
        /// <remarks/>
        EDELIVERY_DOCUMENT_RECEIVED,
        
        /// <remarks/>
        EDELIVERY_DOCUMENT_REGISTERED,
        
        /// <remarks/>
        EDELIVERY_DOCUMENT_REGISTRATION_DENIED,
        
        /// <remarks/>
        EDELIVERY_NOTIFICATION_SENT,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/bes/ws/auditlog/v1")]
    public partial class RequestedServiceType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string serviceOIDField;
        
        private string sPOIDField;
        
        private string sPNameField;
        
        private string serviceNameField;
        
        private string authnRequesterOIDField;
        
        private string adminiOIDField;
        
        private string adminLegalNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ServiceOID {
            get {
                return this.serviceOIDField;
            }
            set {
                this.serviceOIDField = value;
                this.RaisePropertyChanged("ServiceOID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string SPOID {
            get {
                return this.sPOIDField;
            }
            set {
                this.sPOIDField = value;
                this.RaisePropertyChanged("SPOID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string SPName {
            get {
                return this.sPNameField;
            }
            set {
                this.sPNameField = value;
                this.RaisePropertyChanged("SPName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ServiceName {
            get {
                return this.serviceNameField;
            }
            set {
                this.serviceNameField = value;
                this.RaisePropertyChanged("ServiceName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string AuthnRequesterOID {
            get {
                return this.authnRequesterOIDField;
            }
            set {
                this.authnRequesterOIDField = value;
                this.RaisePropertyChanged("AuthnRequesterOID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string AdminiOID {
            get {
                return this.adminiOIDField;
            }
            set {
                this.adminiOIDField = value;
                this.RaisePropertyChanged("AdminiOID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string AdminLegalName {
            get {
                return this.adminLegalNameField;
            }
            set {
                this.adminLegalNameField = value;
                this.RaisePropertyChanged("AdminLegalName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/bes/ws/auditlog/v1")]
    public partial class AdmEmployeeType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string personalIDField;
        
        private PersonIdTypeEnum personalIDTypeField;
        
        private string personNamesField;
        
        private string currentPositionField;
        
        private string parentAdministrationOIDField;
        
        private string parentAdministrationLegalNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string personalID {
            get {
                return this.personalIDField;
            }
            set {
                this.personalIDField = value;
                this.RaisePropertyChanged("personalID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public PersonIdTypeEnum personalIDType {
            get {
                return this.personalIDTypeField;
            }
            set {
                this.personalIDTypeField = value;
                this.RaisePropertyChanged("personalIDType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string personNames {
            get {
                return this.personNamesField;
            }
            set {
                this.personNamesField = value;
                this.RaisePropertyChanged("personNames");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string currentPosition {
            get {
                return this.currentPositionField;
            }
            set {
                this.currentPositionField = value;
                this.RaisePropertyChanged("currentPosition");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string parentAdministrationOID {
            get {
                return this.parentAdministrationOIDField;
            }
            set {
                this.parentAdministrationOIDField = value;
                this.RaisePropertyChanged("parentAdministrationOID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string parentAdministrationLegalName {
            get {
                return this.parentAdministrationLegalNameField;
            }
            set {
                this.parentAdministrationLegalNameField = value;
                this.RaisePropertyChanged("parentAdministrationLegalName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/bes/ws/auditlog/v1")]
    public enum PersonIdTypeEnum {
        
        /// <remarks/>
        ЕГН,
        
        /// <remarks/>
        ЛНЧ,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/bes/ws/auditlog/v1")]
    public partial class ServiceRequesterISType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string requesterIsOIDField;
        
        private string iSNameField;
        
        private string adminOIDField;
        
        private string adminNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string RequesterIsOID {
            get {
                return this.requesterIsOIDField;
            }
            set {
                this.requesterIsOIDField = value;
                this.RaisePropertyChanged("RequesterIsOID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ISName {
            get {
                return this.iSNameField;
            }
            set {
                this.iSNameField = value;
                this.RaisePropertyChanged("ISName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string AdminOID {
            get {
                return this.adminOIDField;
            }
            set {
                this.adminOIDField = value;
                this.RaisePropertyChanged("AdminOID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string AdminName {
            get {
                return this.adminNameField;
            }
            set {
                this.adminNameField = value;
                this.RaisePropertyChanged("AdminName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/bes/ws/auditlog/v1")]
    public partial class PersonalDataAccessAttemptType : EventType {
        
        private string personalDataDescriptionField;
        
        private string subjectIDField;
        
        private ServiceRequesterISType informationSystemField;
        
        private string accessedDataField;
        
        private AdmEmployeeType employeeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string PersonalDataDescription {
            get {
                return this.personalDataDescriptionField;
            }
            set {
                this.personalDataDescriptionField = value;
                this.RaisePropertyChanged("PersonalDataDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string SubjectID {
            get {
                return this.subjectIDField;
            }
            set {
                this.subjectIDField = value;
                this.RaisePropertyChanged("SubjectID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public ServiceRequesterISType InformationSystem {
            get {
                return this.informationSystemField;
            }
            set {
                this.informationSystemField = value;
                this.RaisePropertyChanged("InformationSystem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string AccessedData {
            get {
                return this.accessedDataField;
            }
            set {
                this.accessedDataField = value;
                this.RaisePropertyChanged("AccessedData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public AdmEmployeeType Employee {
            get {
                return this.employeeField;
            }
            set {
                this.employeeField = value;
                this.RaisePropertyChanged("Employee");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RegisterEvent", WrapperNamespace="http://egov.bg/bes/ws/auditlog/v1", IsWrapped=true)]
    public partial class RegisterEvent {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://egov.bg/bes/ws/auditlog/v1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("EAServiceLCEvent")]
        public EPayments.EventRegister.EventRegisterService.EAServiceLCEventType[] EAServiceLCEvent;
        
        public RegisterEvent() {
        }
        
        public RegisterEvent(EPayments.EventRegister.EventRegisterService.EAServiceLCEventType[] EAServiceLCEvent) {
            this.EAServiceLCEvent = EAServiceLCEvent;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RegisterEventSOAPPortChannel : EPayments.EventRegister.EventRegisterService.RegisterEventSOAPPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegisterEventSOAPPortClient : System.ServiceModel.ClientBase<EPayments.EventRegister.EventRegisterService.RegisterEventSOAPPort>, EPayments.EventRegister.EventRegisterService.RegisterEventSOAPPort {
        
        public RegisterEventSOAPPortClient() {
        }
        
        public RegisterEventSOAPPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RegisterEventSOAPPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegisterEventSOAPPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegisterEventSOAPPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void EPayments.EventRegister.EventRegisterService.RegisterEventSOAPPort.RegisterEvent(EPayments.EventRegister.EventRegisterService.RegisterEvent request) {
            base.Channel.RegisterEvent(request);
        }
        
        public void RegisterEvent(EPayments.EventRegister.EventRegisterService.EAServiceLCEventType[] EAServiceLCEvent) {
            EPayments.EventRegister.EventRegisterService.RegisterEvent inValue = new EPayments.EventRegister.EventRegisterService.RegisterEvent();
            inValue.EAServiceLCEvent = EAServiceLCEvent;
            ((EPayments.EventRegister.EventRegisterService.RegisterEventSOAPPort)(this)).RegisterEvent(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task EPayments.EventRegister.EventRegisterService.RegisterEventSOAPPort.RegisterEventAsync(EPayments.EventRegister.EventRegisterService.RegisterEvent request) {
            return base.Channel.RegisterEventAsync(request);
        }
        
        public System.Threading.Tasks.Task RegisterEventAsync(EPayments.EventRegister.EventRegisterService.EAServiceLCEventType[] EAServiceLCEvent) {
            EPayments.EventRegister.EventRegisterService.RegisterEvent inValue = new EPayments.EventRegister.EventRegisterService.RegisterEvent();
            inValue.EAServiceLCEvent = EAServiceLCEvent;
            return ((EPayments.EventRegister.EventRegisterService.RegisterEventSOAPPort)(this)).RegisterEventAsync(inValue);
        }
    }
}
