//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.0.0.0
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;

namespace R_0009_000013
{

	public struct Declarations
	{
		public const string SchemaVersion = "http://ereg.egov.bg/segment/0009-000013";
	}

	[Serializable]
	public enum ModificationTypeNomenclature
	{
		[XmlEnum(Name="Empty")] Empty,
		[XmlEnum(Name="Create")] Create,
		[XmlEnum(Name="Update")] Update,
		[XmlEnum(Name="Delete")] Delete
	}




	[XmlType(TypeName="EntityBasicData",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class EntityBasicData
	{

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlAttribute(AttributeName="modificationType")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public R_7066.ModificationTypeNomenclature __modificationType;
		
		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __modificationTypeSpecified;
		
		[XmlIgnore]
		public R_7066.ModificationTypeNomenclature modificationType
		{ 
			get { return __modificationType; }
			set { __modificationType = value; __modificationTypeSpecified = true; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
        [Newtonsoft.Json.JsonIgnore]
		[XmlElement(ElementName="Name",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __Name;
		
		[XmlIgnore]
		public string Name
		{ 
			get { return __Name; }
			set { __Name = value; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
        [Newtonsoft.Json.JsonIgnore]
		[XmlElement(ElementName="Identifier",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __Identifier;
		
		[XmlIgnore]
		public string Identifier
		{ 
			get { return __Identifier; }
			set { __Identifier = value; }
		}

		public EntityBasicData()
		{
		}
	}
}
