//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.0.0.0
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;

namespace R_10052
{

	public struct Declarations
	{
		public const string SchemaVersion = "http://ereg.egov.bg/segment/R-10052";
	}


	[Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class PaymentRequestErrorCollection : System.Collections.Generic.List<R_10036.PaymentRequestError>
	{
	}



	[XmlRoot(ElementName="PaymentRequestUnacceptedReceipt",Namespace=Declarations.SchemaVersion,IsNullable=false),Serializable]
	[XmlType(TypeName="PaymentRequestUnacceptedReceipt",Namespace=Declarations.SchemaVersion)]
	public partial class PaymentRequestUnacceptedReceipt
	{

		[System.Web.Script.Serialization.ScriptIgnore]
        [Newtonsoft.Json.JsonIgnore]
		[XmlElement(Type=typeof(R_0009_000003.DocumentTypeURI),ElementName="DocumentTypeURI",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public R_0009_000003.DocumentTypeURI __DocumentTypeURI;
		
		[XmlIgnore]
		public R_0009_000003.DocumentTypeURI DocumentTypeURI
		{
			get {return __DocumentTypeURI;}
			set {__DocumentTypeURI = value;}
		}

		[System.Web.Script.Serialization.ScriptIgnore]
        [Newtonsoft.Json.JsonIgnore]
		[XmlElement(ElementName="DocumentTypeName",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __DocumentTypeName;
		
		[XmlIgnore]
		public string DocumentTypeName
		{ 
			get { return __DocumentTypeName; }
			set { __DocumentTypeName = value; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
        [Newtonsoft.Json.JsonIgnore]
		[XmlElement(Type=typeof(PaymentRequestErrors),ElementName="PaymentRequestErrors",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public PaymentRequestErrors __PaymentRequestErrors;
		
		[XmlIgnore]
		public PaymentRequestErrors PaymentRequestErrors
		{
			get {return __PaymentRequestErrors;}
			set {__PaymentRequestErrors = value;}
		}

		[System.Web.Script.Serialization.ScriptIgnore]
        [Newtonsoft.Json.JsonIgnore]
		[XmlElement(ElementName="PaymentRequestValidationTime",Form=XmlSchemaForm.Qualified,DataType="dateTime",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public DateTime? __PaymentRequestValidationTime;
		
		[System.Web.Script.Serialization.ScriptIgnore]
        [Newtonsoft.Json.JsonIgnore]
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __PaymentRequestValidationTimeSpecified { get { return __PaymentRequestValidationTime.HasValue; } }
		
		[XmlIgnore]
		public DateTime? PaymentRequestValidationTime
		{ 
			get { return __PaymentRequestValidationTime; }
			set { __PaymentRequestValidationTime = value; }
		}
		


		[System.Web.Script.Serialization.ScriptIgnore]
        [Newtonsoft.Json.JsonIgnore]
		[XmlElement(Type=typeof(R_10046.PaymentRequest),ElementName="PaymentRequest",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public R_10046.PaymentRequest __PaymentRequest;
		
		[XmlIgnore]
		public R_10046.PaymentRequest PaymentRequest
		{
			get {return __PaymentRequest;}
			set {__PaymentRequest = value;}
		}

		[System.Web.Script.Serialization.ScriptIgnore]
        [Newtonsoft.Json.JsonIgnore]
		[XmlElement(Type=typeof(R_10049.PaymentRequestMultiple),ElementName="PaymentRequestMultiple",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public R_10049.PaymentRequestMultiple __PaymentRequestMultiple;
		
		[XmlIgnore]
		public R_10049.PaymentRequestMultiple PaymentRequestMultiple
		{
			get {return __PaymentRequestMultiple;}
			set {__PaymentRequestMultiple = value;}
		}

		public PaymentRequestUnacceptedReceipt()
		{
		}
	}


	[XmlType(TypeName="PaymentRequestErrors",Namespace=Declarations.SchemaVersion),Serializable]
	public partial class PaymentRequestErrors
	{


		[System.Web.Script.Serialization.ScriptIgnore]
        [Newtonsoft.Json.JsonIgnore]
		[XmlElement(Type=typeof(R_10036.PaymentRequestError),ElementName="PaymentRequestError",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public PaymentRequestErrorCollection __PaymentRequestErrorCollection;
		
		[XmlIgnore]
		public PaymentRequestErrorCollection PaymentRequestErrorCollection
		{
			get
			{
				if (__PaymentRequestErrorCollection == null) __PaymentRequestErrorCollection = new PaymentRequestErrorCollection();
				return __PaymentRequestErrorCollection;
			}
			set {__PaymentRequestErrorCollection = value;}
		}

		public PaymentRequestErrors()
		{
		}
	}
}
