//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.0.0.0
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;

namespace R_10049
{

	public struct Declarations
	{
		public const string SchemaVersion = "http://ereg.egov.bg/segment/R-10049";
	}


	[Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class CreditTransferOrderCollection : System.Collections.Generic.List<R_10034.CreditTransferOrder>
	{
	}



	[XmlRoot(ElementName="PaymentRequestMultiple",Namespace=Declarations.SchemaVersion,IsNullable=false),Serializable]
	[XmlType(TypeName="PaymentRequestMultiple",Namespace=Declarations.SchemaVersion)]
	public partial class PaymentRequestMultiple
	{

		[System.Web.Script.Serialization.ScriptIgnore]
        [Newtonsoft.Json.JsonIgnore]
		[XmlElement(Type=typeof(R_0009_000003.DocumentTypeURI),ElementName="DocumentTypeURI",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public R_0009_000003.DocumentTypeURI __DocumentTypeURI;
		
		[XmlIgnore]
		public R_0009_000003.DocumentTypeURI DocumentTypeURI
		{
			get {return __DocumentTypeURI;}
			set {__DocumentTypeURI = value;}
		}

		[System.Web.Script.Serialization.ScriptIgnore]
        [Newtonsoft.Json.JsonIgnore]
		[XmlElement(ElementName="DocumentTypeName",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __DocumentTypeName;
		
		[XmlIgnore]
		public string DocumentTypeName
		{ 
			get { return __DocumentTypeName; }
			set { __DocumentTypeName = value; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
        [Newtonsoft.Json.JsonIgnore]
		[XmlElement(ElementName="PaymentCode",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __PaymentCode;
		
		[XmlIgnore]
		public string PaymentCode
		{ 
			get { return __PaymentCode; }
			set { __PaymentCode = value; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
        [Newtonsoft.Json.JsonIgnore]
		[XmlElement(ElementName="Currency",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __Currency;
		
		[XmlIgnore]
		public string Currency
		{ 
			get { return __Currency; }
			set { __Currency = value; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
        [Newtonsoft.Json.JsonIgnore]
		[XmlElement(ElementName="PaymentAmount",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="double",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public double __PaymentAmount;
		
		[System.Web.Script.Serialization.ScriptIgnore]
        [Newtonsoft.Json.JsonIgnore]
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __PaymentAmountSpecified;
		
		[XmlIgnore]
		public double PaymentAmount
		{ 
			get { return __PaymentAmount; }
			set { __PaymentAmount = value; __PaymentAmountSpecified = true; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
        [Newtonsoft.Json.JsonIgnore]
		[XmlElement(Type=typeof(R_0009_000002.ElectronicServiceProviderBasicData),ElementName="ElectronicServiceProviderBasicData",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public R_0009_000002.ElectronicServiceProviderBasicData __ElectronicServiceProviderBasicData;
		
		[XmlIgnore]
		public R_0009_000002.ElectronicServiceProviderBasicData ElectronicServiceProviderBasicData
		{
			get {return __ElectronicServiceProviderBasicData;}
			set {__ElectronicServiceProviderBasicData = value;}
		}

		[System.Web.Script.Serialization.ScriptIgnore]
        [Newtonsoft.Json.JsonIgnore]
		[XmlElement(Type=typeof(R_10010.ElectronicServiceProviderBankAccount),ElementName="ElectronicServiceProviderBankAccount",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public R_10010.ElectronicServiceProviderBankAccount __ElectronicServiceProviderBankAccount;
		
		[XmlIgnore]
		public R_10010.ElectronicServiceProviderBankAccount ElectronicServiceProviderBankAccount
		{
			get {return __ElectronicServiceProviderBankAccount;}
			set {__ElectronicServiceProviderBankAccount = value;}
		}

		[System.Web.Script.Serialization.ScriptIgnore]
        [Newtonsoft.Json.JsonIgnore]
		[XmlElement(Type=typeof(R_0009_000015.ElectronicServiceRecipient),ElementName="ElectronicServiceRecipient",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public R_0009_000015.ElectronicServiceRecipient __ElectronicServiceRecipient;
		
		[XmlIgnore]
		public R_0009_000015.ElectronicServiceRecipient ElectronicServiceRecipient
		{
			get {return __ElectronicServiceRecipient;}
			set {__ElectronicServiceRecipient = value;}
		}

		[System.Web.Script.Serialization.ScriptIgnore]
        [Newtonsoft.Json.JsonIgnore]
		[XmlElement(Type=typeof(CreditTransferOrders),ElementName="CreditTransferOrders",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public CreditTransferOrders __CreditTransferOrders;
		
		[XmlIgnore]
		public CreditTransferOrders CreditTransferOrders
		{
			get {return __CreditTransferOrders;}
			set {__CreditTransferOrders = value;}
		}

		[System.Web.Script.Serialization.ScriptIgnore]
        [Newtonsoft.Json.JsonIgnore]
		[XmlElement(ElementName="PaymentRequestExpirationDate",Form=XmlSchemaForm.Qualified,DataType="dateTime",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public DateTime? __PaymentRequestExpirationDate;
		
		[System.Web.Script.Serialization.ScriptIgnore]
        [Newtonsoft.Json.JsonIgnore]
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __PaymentRequestExpirationDateSpecified { get { return __PaymentRequestExpirationDate.HasValue; } }
		
		[XmlIgnore]
		public DateTime? PaymentRequestExpirationDate
		{ 
			get { return __PaymentRequestExpirationDate; }
			set { __PaymentRequestExpirationDate = value; }
		}
		


		[System.Web.Script.Serialization.ScriptIgnore]
        [Newtonsoft.Json.JsonIgnore]
		[XmlElement(ElementName="AdditionalInformationInPaymentRequest",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __AdditionalInformationInPaymentRequest;
		
		[XmlIgnore]
		public string AdditionalInformationInPaymentRequest
		{ 
			get { return __AdditionalInformationInPaymentRequest; }
			set { __AdditionalInformationInPaymentRequest = value; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
        [Newtonsoft.Json.JsonIgnore]
		[XmlElement(ElementName="SUNAUServiceURI",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __SUNAUServiceURI;
		
		[XmlIgnore]
		public string SUNAUServiceURI
		{ 
			get { return __SUNAUServiceURI; }
			set { __SUNAUServiceURI = value; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
        [Newtonsoft.Json.JsonIgnore]
		[XmlElement(ElementName="ElectronicAdministrativeServiceSupplierUriRA",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __ElectronicAdministrativeServiceSupplierUriRA;
		
		[XmlIgnore]
		public string ElectronicAdministrativeServiceSupplierUriRA
		{ 
			get { return __ElectronicAdministrativeServiceSupplierUriRA; }
			set { __ElectronicAdministrativeServiceSupplierUriRA = value; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
        [Newtonsoft.Json.JsonIgnore]
		[XmlElement(ElementName="ElectronicAdministrativeServiceNotificationURL",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __ElectronicAdministrativeServiceNotificationURL;
		
		[XmlIgnore]
		public string ElectronicAdministrativeServiceNotificationURL
		{ 
			get { return __ElectronicAdministrativeServiceNotificationURL; }
			set { __ElectronicAdministrativeServiceNotificationURL = value; }
		}

		public PaymentRequestMultiple()
		{
		}
	}


	[XmlType(TypeName="CreditTransferOrders",Namespace=Declarations.SchemaVersion),Serializable]
	public partial class CreditTransferOrders
	{


		[System.Web.Script.Serialization.ScriptIgnore]
        [Newtonsoft.Json.JsonIgnore]
		[XmlElement(Type=typeof(R_10034.CreditTransferOrder),ElementName="CreditTransferOrder",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public CreditTransferOrderCollection __CreditTransferOrderCollection;
		
		[XmlIgnore]
		public CreditTransferOrderCollection CreditTransferOrderCollection
		{
			get
			{
				if (__CreditTransferOrderCollection == null) __CreditTransferOrderCollection = new CreditTransferOrderCollection();
				return __CreditTransferOrderCollection;
			}
			set {__CreditTransferOrderCollection = value;}
		}

		public CreditTransferOrders()
		{
		}
	}
}
