//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.0.0.0
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;

namespace R_10012
{

	public struct Declarations
	{
		public const string SchemaVersion = "http://ereg.egov.bg/value/R-10012";
	}


}
