//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.0.0.0
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;

namespace R_10034
{

	public struct Declarations
	{
		public const string SchemaVersion = "http://ereg.egov.bg/segment/R-10034";
	}




	[XmlRoot(ElementName="CreditTransferOrder",Namespace=Declarations.SchemaVersion,IsNullable=false),Serializable]
	[XmlType(TypeName="CreditTransferOrder",Namespace=Declarations.SchemaVersion)]
	public partial class CreditTransferOrder
	{

		[System.Web.Script.Serialization.ScriptIgnore]
        [Newtonsoft.Json.JsonIgnore]
		[XmlElement(ElementName="PaymentCode",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __PaymentCode;
		
		[XmlIgnore]
		public string PaymentCode
		{ 
			get { return __PaymentCode; }
			set { __PaymentCode = value; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
        [Newtonsoft.Json.JsonIgnore]
		[XmlElement(ElementName="CreditTransferAmount",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="double",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public double __CreditTransferAmount;
		
		[System.Web.Script.Serialization.ScriptIgnore]
        [Newtonsoft.Json.JsonIgnore]
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __CreditTransferAmountSpecified;
		
		[XmlIgnore]
		public double CreditTransferAmount
		{ 
			get { return __CreditTransferAmount; }
			set { __CreditTransferAmount = value; __CreditTransferAmountSpecified = true; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
        [Newtonsoft.Json.JsonIgnore]
		[XmlElement(ElementName="PaymentReason",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __PaymentReason;
		
		[XmlIgnore]
		public string PaymentReason
		{ 
			get { return __PaymentReason; }
			set { __PaymentReason = value; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
        [Newtonsoft.Json.JsonIgnore]
		[XmlElement(Type=typeof(R_10018.PaymentReference),ElementName="PaymentReference",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public R_10018.PaymentReference __PaymentReference;
		
		[XmlIgnore]
		public R_10018.PaymentReference PaymentReference
		{
			get {return __PaymentReference;}
			set {__PaymentReference = value;}
		}

		[System.Web.Script.Serialization.ScriptIgnore]
        [Newtonsoft.Json.JsonIgnore]
		[XmlElement(Type=typeof(R_10024.PaymentPeriod),ElementName="PaymentPeriod",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public R_10024.PaymentPeriod __PaymentPeriod;
		
		[XmlIgnore]
		public R_10024.PaymentPeriod PaymentPeriod
		{
			get {return __PaymentPeriod;}
			set {__PaymentPeriod = value;}
		}

		public CreditTransferOrder()
		{
		}
	}
}
