//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPayments.CVPosTransaction.CVPosService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.sucardws.bobs.bg/")]
    public partial class sucardError : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int errCodeField;
        
        private bool errCodeFieldSpecified;
        
        private string errMessageField;
        
        private string errStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int errCode {
            get {
                return this.errCodeField;
            }
            set {
                this.errCodeField = value;
                this.RaisePropertyChanged("errCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool errCodeSpecified {
            get {
                return this.errCodeFieldSpecified;
            }
            set {
                this.errCodeFieldSpecified = value;
                this.RaisePropertyChanged("errCodeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string errMessage {
            get {
                return this.errMessageField;
            }
            set {
                this.errMessageField = value;
                this.RaisePropertyChanged("errMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string errStatus {
            get {
                return this.errStatusField;
            }
            set {
                this.errStatusField = value;
                this.RaisePropertyChanged("errStatus");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.sucardws.bobs.bg/")]
    public partial class recStatusUpdates : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string deviceIdnField;
        
        private string errMsgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string deviceIdn {
            get {
                return this.deviceIdnField;
            }
            set {
                this.deviceIdnField = value;
                this.RaisePropertyChanged("deviceIdn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string errMsg {
            get {
                return this.errMsgField;
            }
            set {
                this.errMsgField = value;
                this.RaisePropertyChanged("errMsg");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.sucardws.bobs.bg/")]
    public partial class recDevices : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cityField;
        
        private string countryCodeField;
        
        private string currencyField;
        
        private string deviceIdnField;
        
        private string paymentTypeField;
        
        private string postCodeField;
        
        private string statusField;
        
        private string streetField;
        
        private string streetNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("city");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string countryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
                this.RaisePropertyChanged("countryCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
                this.RaisePropertyChanged("currency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string deviceIdn {
            get {
                return this.deviceIdnField;
            }
            set {
                this.deviceIdnField = value;
                this.RaisePropertyChanged("deviceIdn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string paymentType {
            get {
                return this.paymentTypeField;
            }
            set {
                this.paymentTypeField = value;
                this.RaisePropertyChanged("paymentType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string postCode {
            get {
                return this.postCodeField;
            }
            set {
                this.postCodeField = value;
                this.RaisePropertyChanged("postCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
                this.RaisePropertyChanged("street");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string streetNo {
            get {
                return this.streetNoField;
            }
            set {
                this.streetNoField = value;
                this.RaisePropertyChanged("streetNo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.sucardws.bobs.bg/", ConfigurationName="CVPosService.NapWS")]
    public interface NapWS {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.sucardws.bobs.bg/NapWS/managment_POSRequest", ReplyAction="http://ws.sucardws.bobs.bg/NapWS/managment_POSResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EPayments.CVPosTransaction.CVPosService.sucardError), Action="http://ws.sucardws.bobs.bg/NapWS/managment_POS/Fault/SucardFault", Name="SucardFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EPayments.CVPosTransaction.CVPosService.managment_POSResponse managment_POS(EPayments.CVPosTransaction.CVPosService.managment_POSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.sucardws.bobs.bg/NapWS/managment_POSRequest", ReplyAction="http://ws.sucardws.bobs.bg/NapWS/managment_POSResponse")]
        System.Threading.Tasks.Task<EPayments.CVPosTransaction.CVPosService.managment_POSResponse> managment_POSAsync(EPayments.CVPosTransaction.CVPosService.managment_POSRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.sucardws.bobs.bg/NapWS/transactionsDifferentDaysRequest", ReplyAction="http://ws.sucardws.bobs.bg/NapWS/transactionsDifferentDaysResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EPayments.CVPosTransaction.CVPosService.sucardError), Action="http://ws.sucardws.bobs.bg/NapWS/transactionsDifferentDays/Fault/SucardFault", Name="SucardFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EPayments.CVPosTransaction.CVPosService.transactionsDifferentDaysResponse transactionsDifferentDays(EPayments.CVPosTransaction.CVPosService.transactionsDifferentDaysRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.sucardws.bobs.bg/NapWS/transactionsDifferentDaysRequest", ReplyAction="http://ws.sucardws.bobs.bg/NapWS/transactionsDifferentDaysResponse")]
        System.Threading.Tasks.Task<EPayments.CVPosTransaction.CVPosService.transactionsDifferentDaysResponse> transactionsDifferentDaysAsync(EPayments.CVPosTransaction.CVPosService.transactionsDifferentDaysRequest request);
        
        // CODEGEN: Parameter 'agency' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.sucardws.bobs.bg/NapWS/distributionRevenueAgenciesRequest", ReplyAction="http://ws.sucardws.bobs.bg/NapWS/distributionRevenueAgenciesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EPayments.CVPosTransaction.CVPosService.sucardError), Action="http://ws.sucardws.bobs.bg/NapWS/distributionRevenueAgencies/Fault/SucardFault", Name="SucardFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        EPayments.CVPosTransaction.CVPosService.distributionRevenueAgenciesResponse distributionRevenueAgencies(EPayments.CVPosTransaction.CVPosService.distributionRevenueAgenciesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.sucardws.bobs.bg/NapWS/distributionRevenueAgenciesRequest", ReplyAction="http://ws.sucardws.bobs.bg/NapWS/distributionRevenueAgenciesResponse")]
        System.Threading.Tasks.Task<EPayments.CVPosTransaction.CVPosService.distributionRevenueAgenciesResponse> distributionRevenueAgenciesAsync(EPayments.CVPosTransaction.CVPosService.distributionRevenueAgenciesRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.sucardws.bobs.bg/NapWS/transactionsForDateRequest", ReplyAction="http://ws.sucardws.bobs.bg/NapWS/transactionsForDateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EPayments.CVPosTransaction.CVPosService.sucardError), Action="http://ws.sucardws.bobs.bg/NapWS/transactionsForDate/Fault/SucardFault", Name="SucardFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EPayments.CVPosTransaction.CVPosService.transactionsForDateResponse transactionsForDate(EPayments.CVPosTransaction.CVPosService.transactionsForDateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.sucardws.bobs.bg/NapWS/transactionsForDateRequest", ReplyAction="http://ws.sucardws.bobs.bg/NapWS/transactionsForDateResponse")]
        System.Threading.Tasks.Task<EPayments.CVPosTransaction.CVPosService.transactionsForDateResponse> transactionsForDateAsync(EPayments.CVPosTransaction.CVPosService.transactionsForDateRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.sucardws.bobs.bg/NapWS/transactionsForDateAPIRequest", ReplyAction="http://ws.sucardws.bobs.bg/NapWS/transactionsForDateAPIResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EPayments.CVPosTransaction.CVPosService.sucardError), Action="http://ws.sucardws.bobs.bg/NapWS/transactionsForDateAPI/Fault/SucardFault", Name="SucardFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EPayments.CVPosTransaction.CVPosService.transactionsForDateAPIResponse transactionsForDateAPI(EPayments.CVPosTransaction.CVPosService.transactionsForDateAPIRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.sucardws.bobs.bg/NapWS/transactionsForDateAPIRequest", ReplyAction="http://ws.sucardws.bobs.bg/NapWS/transactionsForDateAPIResponse")]
        System.Threading.Tasks.Task<EPayments.CVPosTransaction.CVPosService.transactionsForDateAPIResponse> transactionsForDateAPIAsync(EPayments.CVPosTransaction.CVPosService.transactionsForDateAPIRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.sucardws.bobs.bg/NapWS/transactionsForDateCurrencyRequest", ReplyAction="http://ws.sucardws.bobs.bg/NapWS/transactionsForDateCurrencyResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EPayments.CVPosTransaction.CVPosService.sucardError), Action="http://ws.sucardws.bobs.bg/NapWS/transactionsForDateCurrency/Fault/SucardFault", Name="SucardFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EPayments.CVPosTransaction.CVPosService.transactionsForDateCurrencyResponse transactionsForDateCurrency(EPayments.CVPosTransaction.CVPosService.transactionsForDateCurrencyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.sucardws.bobs.bg/NapWS/transactionsForDateCurrencyRequest", ReplyAction="http://ws.sucardws.bobs.bg/NapWS/transactionsForDateCurrencyResponse")]
        System.Threading.Tasks.Task<EPayments.CVPosTransaction.CVPosService.transactionsForDateCurrencyResponse> transactionsForDateCurrencyAsync(EPayments.CVPosTransaction.CVPosService.transactionsForDateCurrencyRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="managment_POS", WrapperNamespace="http://ws.sucardws.bobs.bg/", IsWrapped=true)]
    public partial class managment_POSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.sucardws.bobs.bg/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string agency;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.sucardws.bobs.bg/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("recDevices", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EPayments.CVPosTransaction.CVPosService.recDevices[] recDevices;
        
        public managment_POSRequest() {
        }
        
        public managment_POSRequest(string agency, EPayments.CVPosTransaction.CVPosService.recDevices[] recDevices) {
            this.agency = agency;
            this.recDevices = recDevices;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="managment_POSResponse", WrapperNamespace="http://ws.sucardws.bobs.bg/", IsWrapped=true)]
    public partial class managment_POSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.sucardws.bobs.bg/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EPayments.CVPosTransaction.CVPosService.recStatusUpdates[] @return;
        
        public managment_POSResponse() {
        }
        
        public managment_POSResponse(EPayments.CVPosTransaction.CVPosService.recStatusUpdates[] @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.sucardws.bobs.bg/")]
    public partial class recEventTransaction : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string areaOfIssueField;
        
        private string authorizationCodeField;
        
        private string cardBrandField;
        
        private System.DateTime distributionDateField;
        
        private bool distributionDateFieldSpecified;
        
        private string orderIdField;
        
        private string productCategoryField;
        
        private string rrnField;
        
        private System.DateTime settlementDateField;
        
        private bool settlementDateFieldSpecified;
        
        private decimal sumField;
        
        private bool sumFieldSpecified;
        
        private decimal taxField;
        
        private bool taxFieldSpecified;
        
        private decimal taxBoricaField;
        
        private bool taxBoricaFieldSpecified;
        
        private string tidField;
        
        private System.DateTime transactionDateField;
        
        private bool transactionDateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string areaOfIssue {
            get {
                return this.areaOfIssueField;
            }
            set {
                this.areaOfIssueField = value;
                this.RaisePropertyChanged("areaOfIssue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string authorizationCode {
            get {
                return this.authorizationCodeField;
            }
            set {
                this.authorizationCodeField = value;
                this.RaisePropertyChanged("authorizationCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string cardBrand {
            get {
                return this.cardBrandField;
            }
            set {
                this.cardBrandField = value;
                this.RaisePropertyChanged("cardBrand");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime distributionDate {
            get {
                return this.distributionDateField;
            }
            set {
                this.distributionDateField = value;
                this.RaisePropertyChanged("distributionDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool distributionDateSpecified {
            get {
                return this.distributionDateFieldSpecified;
            }
            set {
                this.distributionDateFieldSpecified = value;
                this.RaisePropertyChanged("distributionDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string orderId {
            get {
                return this.orderIdField;
            }
            set {
                this.orderIdField = value;
                this.RaisePropertyChanged("orderId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string productCategory {
            get {
                return this.productCategoryField;
            }
            set {
                this.productCategoryField = value;
                this.RaisePropertyChanged("productCategory");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string rrn {
            get {
                return this.rrnField;
            }
            set {
                this.rrnField = value;
                this.RaisePropertyChanged("rrn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public System.DateTime settlementDate {
            get {
                return this.settlementDateField;
            }
            set {
                this.settlementDateField = value;
                this.RaisePropertyChanged("settlementDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool settlementDateSpecified {
            get {
                return this.settlementDateFieldSpecified;
            }
            set {
                this.settlementDateFieldSpecified = value;
                this.RaisePropertyChanged("settlementDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public decimal sum {
            get {
                return this.sumField;
            }
            set {
                this.sumField = value;
                this.RaisePropertyChanged("sum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sumSpecified {
            get {
                return this.sumFieldSpecified;
            }
            set {
                this.sumFieldSpecified = value;
                this.RaisePropertyChanged("sumSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public decimal tax {
            get {
                return this.taxField;
            }
            set {
                this.taxField = value;
                this.RaisePropertyChanged("tax");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool taxSpecified {
            get {
                return this.taxFieldSpecified;
            }
            set {
                this.taxFieldSpecified = value;
                this.RaisePropertyChanged("taxSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public decimal taxBorica {
            get {
                return this.taxBoricaField;
            }
            set {
                this.taxBoricaField = value;
                this.RaisePropertyChanged("taxBorica");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool taxBoricaSpecified {
            get {
                return this.taxBoricaFieldSpecified;
            }
            set {
                this.taxBoricaFieldSpecified = value;
                this.RaisePropertyChanged("taxBoricaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string tid {
            get {
                return this.tidField;
            }
            set {
                this.tidField = value;
                this.RaisePropertyChanged("tid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public System.DateTime transactionDate {
            get {
                return this.transactionDateField;
            }
            set {
                this.transactionDateField = value;
                this.RaisePropertyChanged("transactionDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transactionDateSpecified {
            get {
                return this.transactionDateFieldSpecified;
            }
            set {
                this.transactionDateFieldSpecified = value;
                this.RaisePropertyChanged("transactionDateSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="transactionsDifferentDays", WrapperNamespace="http://ws.sucardws.bobs.bg/", IsWrapped=true)]
    public partial class transactionsDifferentDaysRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.sucardws.bobs.bg/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string agency;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.sucardws.bobs.bg/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string unequality;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.sucardws.bobs.bg/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime dateEvent;
        
        public transactionsDifferentDaysRequest() {
        }
        
        public transactionsDifferentDaysRequest(string agency, string unequality, System.DateTime dateEvent) {
            this.agency = agency;
            this.unequality = unequality;
            this.dateEvent = dateEvent;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="transactionsDifferentDaysResponse", WrapperNamespace="http://ws.sucardws.bobs.bg/", IsWrapped=true)]
    public partial class transactionsDifferentDaysResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.sucardws.bobs.bg/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EPayments.CVPosTransaction.CVPosService.recEventTransaction[] @return;
        
        public transactionsDifferentDaysResponse() {
        }
        
        public transactionsDifferentDaysResponse(EPayments.CVPosTransaction.CVPosService.recEventTransaction[] @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.sucardws.bobs.bg/")]
    public partial class recTransaction : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string authorizationCodeField;
        
        private string orderIdField;
        
        private string rrnField;
        
        private decimal sumField;
        
        private bool sumFieldSpecified;
        
        private string tidField;
        
        private System.DateTime transactionDateField;
        
        private bool transactionDateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string authorizationCode {
            get {
                return this.authorizationCodeField;
            }
            set {
                this.authorizationCodeField = value;
                this.RaisePropertyChanged("authorizationCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string orderId {
            get {
                return this.orderIdField;
            }
            set {
                this.orderIdField = value;
                this.RaisePropertyChanged("orderId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string rrn {
            get {
                return this.rrnField;
            }
            set {
                this.rrnField = value;
                this.RaisePropertyChanged("rrn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public decimal sum {
            get {
                return this.sumField;
            }
            set {
                this.sumField = value;
                this.RaisePropertyChanged("sum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sumSpecified {
            get {
                return this.sumFieldSpecified;
            }
            set {
                this.sumFieldSpecified = value;
                this.RaisePropertyChanged("sumSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string tid {
            get {
                return this.tidField;
            }
            set {
                this.tidField = value;
                this.RaisePropertyChanged("tid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public System.DateTime transactionDate {
            get {
                return this.transactionDateField;
            }
            set {
                this.transactionDateField = value;
                this.RaisePropertyChanged("transactionDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transactionDateSpecified {
            get {
                return this.transactionDateFieldSpecified;
            }
            set {
                this.transactionDateFieldSpecified = value;
                this.RaisePropertyChanged("transactionDateSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.sucardws.bobs.bg/")]
    public partial class recDistributedAmount : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private decimal sumField;
        
        private bool sumFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal sum {
            get {
                return this.sumField;
            }
            set {
                this.sumField = value;
                this.RaisePropertyChanged("sum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sumSpecified {
            get {
                return this.sumFieldSpecified;
            }
            set {
                this.sumFieldSpecified = value;
                this.RaisePropertyChanged("sumSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="distributionRevenueAgencies", WrapperNamespace="http://ws.sucardws.bobs.bg/", IsWrapped=true)]
    public partial class distributionRevenueAgenciesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.sucardws.bobs.bg/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string agency;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.sucardws.bobs.bg/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime distributedDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.sucardws.bobs.bg/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int num;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.sucardws.bobs.bg/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute("transactions", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EPayments.CVPosTransaction.CVPosService.recTransaction[] transactions;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.sucardws.bobs.bg/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal totalSum;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.sucardws.bobs.bg/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute("distributedAmounts", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EPayments.CVPosTransaction.CVPosService.recDistributedAmount[] distributedAmounts;
        
        public distributionRevenueAgenciesRequest() {
        }
        
        public distributionRevenueAgenciesRequest(string agency, System.DateTime distributedDate, int num, EPayments.CVPosTransaction.CVPosService.recTransaction[] transactions, decimal totalSum, EPayments.CVPosTransaction.CVPosService.recDistributedAmount[] distributedAmounts) {
            this.agency = agency;
            this.distributedDate = distributedDate;
            this.num = num;
            this.transactions = transactions;
            this.totalSum = totalSum;
            this.distributedAmounts = distributedAmounts;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="distributionRevenueAgenciesResponse", WrapperNamespace="http://ws.sucardws.bobs.bg/", IsWrapped=true)]
    public partial class distributionRevenueAgenciesResponse {
        
        public distributionRevenueAgenciesResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="transactionsForDate", WrapperNamespace="http://ws.sucardws.bobs.bg/", IsWrapped=true)]
    public partial class transactionsForDateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.sucardws.bobs.bg/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string agency;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.sucardws.bobs.bg/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @event;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.sucardws.bobs.bg/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime dateEvent;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.sucardws.bobs.bg/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tid;
        
        public transactionsForDateRequest() {
        }
        
        public transactionsForDateRequest(string agency, string @event, System.DateTime dateEvent, string tid) {
            this.agency = agency;
            this.@event = @event;
            this.dateEvent = dateEvent;
            this.tid = tid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="transactionsForDateResponse", WrapperNamespace="http://ws.sucardws.bobs.bg/", IsWrapped=true)]
    public partial class transactionsForDateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.sucardws.bobs.bg/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EPayments.CVPosTransaction.CVPosService.recEventTransaction[] @return;
        
        public transactionsForDateResponse() {
        }
        
        public transactionsForDateResponse(EPayments.CVPosTransaction.CVPosService.recEventTransaction[] @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.sucardws.bobs.bg/")]
    public partial class recEventTransactionAPIResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private recEventTransactionAPI[] listRecEventTransactionAPIField;
        
        private int totalTrnzField;
        
        private bool totalTrnzFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("listRecEventTransactionAPI", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public recEventTransactionAPI[] listRecEventTransactionAPI {
            get {
                return this.listRecEventTransactionAPIField;
            }
            set {
                this.listRecEventTransactionAPIField = value;
                this.RaisePropertyChanged("listRecEventTransactionAPI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int totalTrnz {
            get {
                return this.totalTrnzField;
            }
            set {
                this.totalTrnzField = value;
                this.RaisePropertyChanged("totalTrnz");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totalTrnzSpecified {
            get {
                return this.totalTrnzFieldSpecified;
            }
            set {
                this.totalTrnzFieldSpecified = value;
                this.RaisePropertyChanged("totalTrnzSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.sucardws.bobs.bg/")]
    public partial class recEventTransactionAPI : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string areaOfIssueField;
        
        private string authorizationCodeField;
        
        private string cardBrandField;
        
        private System.DateTime distributionDateField;
        
        private bool distributionDateFieldSpecified;
        
        private string orderIdField;
        
        private string paymentTypeField;
        
        private string productCategoryField;
        
        private string rrnField;
        
        private System.DateTime settlementDateField;
        
        private bool settlementDateFieldSpecified;
        
        private decimal sumField;
        
        private bool sumFieldSpecified;
        
        private decimal taxField;
        
        private bool taxFieldSpecified;
        
        private decimal taxBoricaField;
        
        private bool taxBoricaFieldSpecified;
        
        private string tidField;
        
        private System.DateTime transactionDateField;
        
        private bool transactionDateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string areaOfIssue {
            get {
                return this.areaOfIssueField;
            }
            set {
                this.areaOfIssueField = value;
                this.RaisePropertyChanged("areaOfIssue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string authorizationCode {
            get {
                return this.authorizationCodeField;
            }
            set {
                this.authorizationCodeField = value;
                this.RaisePropertyChanged("authorizationCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string cardBrand {
            get {
                return this.cardBrandField;
            }
            set {
                this.cardBrandField = value;
                this.RaisePropertyChanged("cardBrand");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime distributionDate {
            get {
                return this.distributionDateField;
            }
            set {
                this.distributionDateField = value;
                this.RaisePropertyChanged("distributionDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool distributionDateSpecified {
            get {
                return this.distributionDateFieldSpecified;
            }
            set {
                this.distributionDateFieldSpecified = value;
                this.RaisePropertyChanged("distributionDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string orderId {
            get {
                return this.orderIdField;
            }
            set {
                this.orderIdField = value;
                this.RaisePropertyChanged("orderId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string paymentType {
            get {
                return this.paymentTypeField;
            }
            set {
                this.paymentTypeField = value;
                this.RaisePropertyChanged("paymentType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string productCategory {
            get {
                return this.productCategoryField;
            }
            set {
                this.productCategoryField = value;
                this.RaisePropertyChanged("productCategory");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string rrn {
            get {
                return this.rrnField;
            }
            set {
                this.rrnField = value;
                this.RaisePropertyChanged("rrn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public System.DateTime settlementDate {
            get {
                return this.settlementDateField;
            }
            set {
                this.settlementDateField = value;
                this.RaisePropertyChanged("settlementDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool settlementDateSpecified {
            get {
                return this.settlementDateFieldSpecified;
            }
            set {
                this.settlementDateFieldSpecified = value;
                this.RaisePropertyChanged("settlementDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public decimal sum {
            get {
                return this.sumField;
            }
            set {
                this.sumField = value;
                this.RaisePropertyChanged("sum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sumSpecified {
            get {
                return this.sumFieldSpecified;
            }
            set {
                this.sumFieldSpecified = value;
                this.RaisePropertyChanged("sumSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public decimal tax {
            get {
                return this.taxField;
            }
            set {
                this.taxField = value;
                this.RaisePropertyChanged("tax");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool taxSpecified {
            get {
                return this.taxFieldSpecified;
            }
            set {
                this.taxFieldSpecified = value;
                this.RaisePropertyChanged("taxSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public decimal taxBorica {
            get {
                return this.taxBoricaField;
            }
            set {
                this.taxBoricaField = value;
                this.RaisePropertyChanged("taxBorica");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool taxBoricaSpecified {
            get {
                return this.taxBoricaFieldSpecified;
            }
            set {
                this.taxBoricaFieldSpecified = value;
                this.RaisePropertyChanged("taxBoricaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string tid {
            get {
                return this.tidField;
            }
            set {
                this.tidField = value;
                this.RaisePropertyChanged("tid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public System.DateTime transactionDate {
            get {
                return this.transactionDateField;
            }
            set {
                this.transactionDateField = value;
                this.RaisePropertyChanged("transactionDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transactionDateSpecified {
            get {
                return this.transactionDateFieldSpecified;
            }
            set {
                this.transactionDateFieldSpecified = value;
                this.RaisePropertyChanged("transactionDateSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="transactionsForDateAPI", WrapperNamespace="http://ws.sucardws.bobs.bg/", IsWrapped=true)]
    public partial class transactionsForDateAPIRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.sucardws.bobs.bg/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string agency;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.sucardws.bobs.bg/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @event;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.sucardws.bobs.bg/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime dateEvent;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.sucardws.bobs.bg/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.sucardws.bobs.bg/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string requestId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.sucardws.bobs.bg/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numberTrnz;
        
        public transactionsForDateAPIRequest() {
        }
        
        public transactionsForDateAPIRequest(string agency, string @event, System.DateTime dateEvent, string tid, string requestId, string numberTrnz) {
            this.agency = agency;
            this.@event = @event;
            this.dateEvent = dateEvent;
            this.tid = tid;
            this.requestId = requestId;
            this.numberTrnz = numberTrnz;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="transactionsForDateAPIResponse", WrapperNamespace="http://ws.sucardws.bobs.bg/", IsWrapped=true)]
    public partial class transactionsForDateAPIResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.sucardws.bobs.bg/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EPayments.CVPosTransaction.CVPosService.recEventTransactionAPIResult @return;
        
        public transactionsForDateAPIResponse() {
        }
        
        public transactionsForDateAPIResponse(EPayments.CVPosTransaction.CVPosService.recEventTransactionAPIResult @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.sucardws.bobs.bg/")]
    public partial class recEventTransactionEUR : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string areaOfIssueField;
        
        private string authorizationCodeField;
        
        private string cardBrandField;
        
        private System.DateTime distributionDateField;
        
        private bool distributionDateFieldSpecified;
        
        private string orderIdField;
        
        private string productCategoryField;
        
        private string rrnField;
        
        private System.DateTime settlementDateField;
        
        private bool settlementDateFieldSpecified;
        
        private decimal sumField;
        
        private bool sumFieldSpecified;
        
        private decimal sumEURField;
        
        private bool sumEURFieldSpecified;
        
        private decimal taxField;
        
        private bool taxFieldSpecified;
        
        private decimal taxBoricaField;
        
        private bool taxBoricaFieldSpecified;
        
        private decimal taxEURField;
        
        private bool taxEURFieldSpecified;
        
        private string tidField;
        
        private System.DateTime transactionDateField;
        
        private bool transactionDateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string areaOfIssue {
            get {
                return this.areaOfIssueField;
            }
            set {
                this.areaOfIssueField = value;
                this.RaisePropertyChanged("areaOfIssue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string authorizationCode {
            get {
                return this.authorizationCodeField;
            }
            set {
                this.authorizationCodeField = value;
                this.RaisePropertyChanged("authorizationCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string cardBrand {
            get {
                return this.cardBrandField;
            }
            set {
                this.cardBrandField = value;
                this.RaisePropertyChanged("cardBrand");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime distributionDate {
            get {
                return this.distributionDateField;
            }
            set {
                this.distributionDateField = value;
                this.RaisePropertyChanged("distributionDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool distributionDateSpecified {
            get {
                return this.distributionDateFieldSpecified;
            }
            set {
                this.distributionDateFieldSpecified = value;
                this.RaisePropertyChanged("distributionDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string orderId {
            get {
                return this.orderIdField;
            }
            set {
                this.orderIdField = value;
                this.RaisePropertyChanged("orderId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string productCategory {
            get {
                return this.productCategoryField;
            }
            set {
                this.productCategoryField = value;
                this.RaisePropertyChanged("productCategory");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string rrn {
            get {
                return this.rrnField;
            }
            set {
                this.rrnField = value;
                this.RaisePropertyChanged("rrn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public System.DateTime settlementDate {
            get {
                return this.settlementDateField;
            }
            set {
                this.settlementDateField = value;
                this.RaisePropertyChanged("settlementDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool settlementDateSpecified {
            get {
                return this.settlementDateFieldSpecified;
            }
            set {
                this.settlementDateFieldSpecified = value;
                this.RaisePropertyChanged("settlementDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public decimal sum {
            get {
                return this.sumField;
            }
            set {
                this.sumField = value;
                this.RaisePropertyChanged("sum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sumSpecified {
            get {
                return this.sumFieldSpecified;
            }
            set {
                this.sumFieldSpecified = value;
                this.RaisePropertyChanged("sumSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public decimal sumEUR {
            get {
                return this.sumEURField;
            }
            set {
                this.sumEURField = value;
                this.RaisePropertyChanged("sumEUR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sumEURSpecified {
            get {
                return this.sumEURFieldSpecified;
            }
            set {
                this.sumEURFieldSpecified = value;
                this.RaisePropertyChanged("sumEURSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public decimal tax {
            get {
                return this.taxField;
            }
            set {
                this.taxField = value;
                this.RaisePropertyChanged("tax");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool taxSpecified {
            get {
                return this.taxFieldSpecified;
            }
            set {
                this.taxFieldSpecified = value;
                this.RaisePropertyChanged("taxSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public decimal taxBorica {
            get {
                return this.taxBoricaField;
            }
            set {
                this.taxBoricaField = value;
                this.RaisePropertyChanged("taxBorica");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool taxBoricaSpecified {
            get {
                return this.taxBoricaFieldSpecified;
            }
            set {
                this.taxBoricaFieldSpecified = value;
                this.RaisePropertyChanged("taxBoricaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public decimal taxEUR {
            get {
                return this.taxEURField;
            }
            set {
                this.taxEURField = value;
                this.RaisePropertyChanged("taxEUR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool taxEURSpecified {
            get {
                return this.taxEURFieldSpecified;
            }
            set {
                this.taxEURFieldSpecified = value;
                this.RaisePropertyChanged("taxEURSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string tid {
            get {
                return this.tidField;
            }
            set {
                this.tidField = value;
                this.RaisePropertyChanged("tid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public System.DateTime transactionDate {
            get {
                return this.transactionDateField;
            }
            set {
                this.transactionDateField = value;
                this.RaisePropertyChanged("transactionDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transactionDateSpecified {
            get {
                return this.transactionDateFieldSpecified;
            }
            set {
                this.transactionDateFieldSpecified = value;
                this.RaisePropertyChanged("transactionDateSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="transactionsForDateCurrency", WrapperNamespace="http://ws.sucardws.bobs.bg/", IsWrapped=true)]
    public partial class transactionsForDateCurrencyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.sucardws.bobs.bg/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string agency;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.sucardws.bobs.bg/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @event;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.sucardws.bobs.bg/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime dateEvent;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.sucardws.bobs.bg/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tid;
        
        public transactionsForDateCurrencyRequest() {
        }
        
        public transactionsForDateCurrencyRequest(string agency, string @event, System.DateTime dateEvent, string tid) {
            this.agency = agency;
            this.@event = @event;
            this.dateEvent = dateEvent;
            this.tid = tid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="transactionsForDateCurrencyResponse", WrapperNamespace="http://ws.sucardws.bobs.bg/", IsWrapped=true)]
    public partial class transactionsForDateCurrencyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.sucardws.bobs.bg/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EPayments.CVPosTransaction.CVPosService.recEventTransactionEUR[] @return;
        
        public transactionsForDateCurrencyResponse() {
        }
        
        public transactionsForDateCurrencyResponse(EPayments.CVPosTransaction.CVPosService.recEventTransactionEUR[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NapWSChannel : EPayments.CVPosTransaction.CVPosService.NapWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NapWSClient : System.ServiceModel.ClientBase<EPayments.CVPosTransaction.CVPosService.NapWS>, EPayments.CVPosTransaction.CVPosService.NapWS {
        
        public NapWSClient() {
        }
        
        public NapWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NapWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NapWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NapWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EPayments.CVPosTransaction.CVPosService.managment_POSResponse EPayments.CVPosTransaction.CVPosService.NapWS.managment_POS(EPayments.CVPosTransaction.CVPosService.managment_POSRequest request) {
            return base.Channel.managment_POS(request);
        }
        
        public EPayments.CVPosTransaction.CVPosService.recStatusUpdates[] managment_POS(string agency, EPayments.CVPosTransaction.CVPosService.recDevices[] recDevices) {
            EPayments.CVPosTransaction.CVPosService.managment_POSRequest inValue = new EPayments.CVPosTransaction.CVPosService.managment_POSRequest();
            inValue.agency = agency;
            inValue.recDevices = recDevices;
            EPayments.CVPosTransaction.CVPosService.managment_POSResponse retVal = ((EPayments.CVPosTransaction.CVPosService.NapWS)(this)).managment_POS(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EPayments.CVPosTransaction.CVPosService.managment_POSResponse> EPayments.CVPosTransaction.CVPosService.NapWS.managment_POSAsync(EPayments.CVPosTransaction.CVPosService.managment_POSRequest request) {
            return base.Channel.managment_POSAsync(request);
        }
        
        public System.Threading.Tasks.Task<EPayments.CVPosTransaction.CVPosService.managment_POSResponse> managment_POSAsync(string agency, EPayments.CVPosTransaction.CVPosService.recDevices[] recDevices) {
            EPayments.CVPosTransaction.CVPosService.managment_POSRequest inValue = new EPayments.CVPosTransaction.CVPosService.managment_POSRequest();
            inValue.agency = agency;
            inValue.recDevices = recDevices;
            return ((EPayments.CVPosTransaction.CVPosService.NapWS)(this)).managment_POSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EPayments.CVPosTransaction.CVPosService.transactionsDifferentDaysResponse EPayments.CVPosTransaction.CVPosService.NapWS.transactionsDifferentDays(EPayments.CVPosTransaction.CVPosService.transactionsDifferentDaysRequest request) {
            return base.Channel.transactionsDifferentDays(request);
        }
        
        public EPayments.CVPosTransaction.CVPosService.recEventTransaction[] transactionsDifferentDays(string agency, string unequality, System.DateTime dateEvent) {
            EPayments.CVPosTransaction.CVPosService.transactionsDifferentDaysRequest inValue = new EPayments.CVPosTransaction.CVPosService.transactionsDifferentDaysRequest();
            inValue.agency = agency;
            inValue.unequality = unequality;
            inValue.dateEvent = dateEvent;
            EPayments.CVPosTransaction.CVPosService.transactionsDifferentDaysResponse retVal = ((EPayments.CVPosTransaction.CVPosService.NapWS)(this)).transactionsDifferentDays(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EPayments.CVPosTransaction.CVPosService.transactionsDifferentDaysResponse> EPayments.CVPosTransaction.CVPosService.NapWS.transactionsDifferentDaysAsync(EPayments.CVPosTransaction.CVPosService.transactionsDifferentDaysRequest request) {
            return base.Channel.transactionsDifferentDaysAsync(request);
        }
        
        public System.Threading.Tasks.Task<EPayments.CVPosTransaction.CVPosService.transactionsDifferentDaysResponse> transactionsDifferentDaysAsync(string agency, string unequality, System.DateTime dateEvent) {
            EPayments.CVPosTransaction.CVPosService.transactionsDifferentDaysRequest inValue = new EPayments.CVPosTransaction.CVPosService.transactionsDifferentDaysRequest();
            inValue.agency = agency;
            inValue.unequality = unequality;
            inValue.dateEvent = dateEvent;
            return ((EPayments.CVPosTransaction.CVPosService.NapWS)(this)).transactionsDifferentDaysAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EPayments.CVPosTransaction.CVPosService.distributionRevenueAgenciesResponse EPayments.CVPosTransaction.CVPosService.NapWS.distributionRevenueAgencies(EPayments.CVPosTransaction.CVPosService.distributionRevenueAgenciesRequest request) {
            return base.Channel.distributionRevenueAgencies(request);
        }
        
        public void distributionRevenueAgencies(string agency, System.DateTime distributedDate, int num, EPayments.CVPosTransaction.CVPosService.recTransaction[] transactions, decimal totalSum, EPayments.CVPosTransaction.CVPosService.recDistributedAmount[] distributedAmounts) {
            EPayments.CVPosTransaction.CVPosService.distributionRevenueAgenciesRequest inValue = new EPayments.CVPosTransaction.CVPosService.distributionRevenueAgenciesRequest();
            inValue.agency = agency;
            inValue.distributedDate = distributedDate;
            inValue.num = num;
            inValue.transactions = transactions;
            inValue.totalSum = totalSum;
            inValue.distributedAmounts = distributedAmounts;
            EPayments.CVPosTransaction.CVPosService.distributionRevenueAgenciesResponse retVal = ((EPayments.CVPosTransaction.CVPosService.NapWS)(this)).distributionRevenueAgencies(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EPayments.CVPosTransaction.CVPosService.distributionRevenueAgenciesResponse> EPayments.CVPosTransaction.CVPosService.NapWS.distributionRevenueAgenciesAsync(EPayments.CVPosTransaction.CVPosService.distributionRevenueAgenciesRequest request) {
            return base.Channel.distributionRevenueAgenciesAsync(request);
        }
        
        public System.Threading.Tasks.Task<EPayments.CVPosTransaction.CVPosService.distributionRevenueAgenciesResponse> distributionRevenueAgenciesAsync(string agency, System.DateTime distributedDate, int num, EPayments.CVPosTransaction.CVPosService.recTransaction[] transactions, decimal totalSum, EPayments.CVPosTransaction.CVPosService.recDistributedAmount[] distributedAmounts) {
            EPayments.CVPosTransaction.CVPosService.distributionRevenueAgenciesRequest inValue = new EPayments.CVPosTransaction.CVPosService.distributionRevenueAgenciesRequest();
            inValue.agency = agency;
            inValue.distributedDate = distributedDate;
            inValue.num = num;
            inValue.transactions = transactions;
            inValue.totalSum = totalSum;
            inValue.distributedAmounts = distributedAmounts;
            return ((EPayments.CVPosTransaction.CVPosService.NapWS)(this)).distributionRevenueAgenciesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EPayments.CVPosTransaction.CVPosService.transactionsForDateResponse EPayments.CVPosTransaction.CVPosService.NapWS.transactionsForDate(EPayments.CVPosTransaction.CVPosService.transactionsForDateRequest request) {
            return base.Channel.transactionsForDate(request);
        }
        
        public EPayments.CVPosTransaction.CVPosService.recEventTransaction[] transactionsForDate(string agency, string @event, System.DateTime dateEvent, string tid) {
            EPayments.CVPosTransaction.CVPosService.transactionsForDateRequest inValue = new EPayments.CVPosTransaction.CVPosService.transactionsForDateRequest();
            inValue.agency = agency;
            inValue.@event = @event;
            inValue.dateEvent = dateEvent;
            inValue.tid = tid;
            EPayments.CVPosTransaction.CVPosService.transactionsForDateResponse retVal = ((EPayments.CVPosTransaction.CVPosService.NapWS)(this)).transactionsForDate(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EPayments.CVPosTransaction.CVPosService.transactionsForDateResponse> EPayments.CVPosTransaction.CVPosService.NapWS.transactionsForDateAsync(EPayments.CVPosTransaction.CVPosService.transactionsForDateRequest request) {
            return base.Channel.transactionsForDateAsync(request);
        }
        
        public System.Threading.Tasks.Task<EPayments.CVPosTransaction.CVPosService.transactionsForDateResponse> transactionsForDateAsync(string agency, string @event, System.DateTime dateEvent, string tid) {
            EPayments.CVPosTransaction.CVPosService.transactionsForDateRequest inValue = new EPayments.CVPosTransaction.CVPosService.transactionsForDateRequest();
            inValue.agency = agency;
            inValue.@event = @event;
            inValue.dateEvent = dateEvent;
            inValue.tid = tid;
            return ((EPayments.CVPosTransaction.CVPosService.NapWS)(this)).transactionsForDateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EPayments.CVPosTransaction.CVPosService.transactionsForDateAPIResponse EPayments.CVPosTransaction.CVPosService.NapWS.transactionsForDateAPI(EPayments.CVPosTransaction.CVPosService.transactionsForDateAPIRequest request) {
            return base.Channel.transactionsForDateAPI(request);
        }
        
        public EPayments.CVPosTransaction.CVPosService.recEventTransactionAPIResult transactionsForDateAPI(string agency, string @event, System.DateTime dateEvent, string tid, string requestId, string numberTrnz) {
            EPayments.CVPosTransaction.CVPosService.transactionsForDateAPIRequest inValue = new EPayments.CVPosTransaction.CVPosService.transactionsForDateAPIRequest();
            inValue.agency = agency;
            inValue.@event = @event;
            inValue.dateEvent = dateEvent;
            inValue.tid = tid;
            inValue.requestId = requestId;
            inValue.numberTrnz = numberTrnz;
            EPayments.CVPosTransaction.CVPosService.transactionsForDateAPIResponse retVal = ((EPayments.CVPosTransaction.CVPosService.NapWS)(this)).transactionsForDateAPI(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EPayments.CVPosTransaction.CVPosService.transactionsForDateAPIResponse> EPayments.CVPosTransaction.CVPosService.NapWS.transactionsForDateAPIAsync(EPayments.CVPosTransaction.CVPosService.transactionsForDateAPIRequest request) {
            return base.Channel.transactionsForDateAPIAsync(request);
        }
        
        public System.Threading.Tasks.Task<EPayments.CVPosTransaction.CVPosService.transactionsForDateAPIResponse> transactionsForDateAPIAsync(string agency, string @event, System.DateTime dateEvent, string tid, string requestId, string numberTrnz) {
            EPayments.CVPosTransaction.CVPosService.transactionsForDateAPIRequest inValue = new EPayments.CVPosTransaction.CVPosService.transactionsForDateAPIRequest();
            inValue.agency = agency;
            inValue.@event = @event;
            inValue.dateEvent = dateEvent;
            inValue.tid = tid;
            inValue.requestId = requestId;
            inValue.numberTrnz = numberTrnz;
            return ((EPayments.CVPosTransaction.CVPosService.NapWS)(this)).transactionsForDateAPIAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EPayments.CVPosTransaction.CVPosService.transactionsForDateCurrencyResponse EPayments.CVPosTransaction.CVPosService.NapWS.transactionsForDateCurrency(EPayments.CVPosTransaction.CVPosService.transactionsForDateCurrencyRequest request) {
            return base.Channel.transactionsForDateCurrency(request);
        }
        
        public EPayments.CVPosTransaction.CVPosService.recEventTransactionEUR[] transactionsForDateCurrency(string agency, string @event, System.DateTime dateEvent, string tid) {
            EPayments.CVPosTransaction.CVPosService.transactionsForDateCurrencyRequest inValue = new EPayments.CVPosTransaction.CVPosService.transactionsForDateCurrencyRequest();
            inValue.agency = agency;
            inValue.@event = @event;
            inValue.dateEvent = dateEvent;
            inValue.tid = tid;
            EPayments.CVPosTransaction.CVPosService.transactionsForDateCurrencyResponse retVal = ((EPayments.CVPosTransaction.CVPosService.NapWS)(this)).transactionsForDateCurrency(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EPayments.CVPosTransaction.CVPosService.transactionsForDateCurrencyResponse> EPayments.CVPosTransaction.CVPosService.NapWS.transactionsForDateCurrencyAsync(EPayments.CVPosTransaction.CVPosService.transactionsForDateCurrencyRequest request) {
            return base.Channel.transactionsForDateCurrencyAsync(request);
        }
        
        public System.Threading.Tasks.Task<EPayments.CVPosTransaction.CVPosService.transactionsForDateCurrencyResponse> transactionsForDateCurrencyAsync(string agency, string @event, System.DateTime dateEvent, string tid) {
            EPayments.CVPosTransaction.CVPosService.transactionsForDateCurrencyRequest inValue = new EPayments.CVPosTransaction.CVPosService.transactionsForDateCurrencyRequest();
            inValue.agency = agency;
            inValue.@event = @event;
            inValue.dateEvent = dateEvent;
            inValue.tid = tid;
            return ((EPayments.CVPosTransaction.CVPosService.NapWS)(this)).transactionsForDateCurrencyAsync(inValue);
        }
    }
}
